import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {Asset,History,Location,User} from '@/shared/types';
import type {Incident,LocationDetail,OperationsSummary,SystemSettings} from '@/shared/product';
import {hasPermission} from '@/shared/permissions';
import {requirePermission,actionPermission} from './permissions';
import {query,transaction} from './db';
import {AppError} from './errors';
import {parse,uuidSchema,assetIdSchema} from './validation';
import {assetProjection,assetFrom,idempotent,performAssetAction} from './services';
import {csv} from './csv';
const clean=<T>(value:T):T=>JSON.parse(JSON.stringify(value));
const incidentProjection=`i.id,i.number,i.title,i.description,a.asset_id AS "assetId",a.name AS "assetName",i.assigned_to AS "assignedTo",assigned.name AS "assignedName",i.status,i.priority,i.external_reference AS "externalReference",i.version,i.created_at AS "createdAt",i.updated_at AS "updatedAt",u.name AS author`;
const incidentFrom='FROM incidents i LEFT JOIN assets a ON a.id=i.asset_id LEFT JOIN users assigned ON assigned.id=i.assigned_to JOIN users u ON u.id=i.created_by';
export async function listIncidents(params:URLSearchParams){const q=params.get('q')?.trim()??'';if(q.length>200)throw new AppError(400,'Wyszukiwanie może mieć najwyżej 200 znaków.');const status=params.get('status')??'',assetId=params.get('assetId')??'';if(assetId)parse(assetIdSchema,assetId);return clean((await query<Incident>(`SELECT ${incidentProjection} ${incidentFrom} WHERE ($1='' OR concat_ws(' ',i.number,i.title,i.description,i.external_reference,a.asset_id,a.name) ILIKE '%'||$1||'%') AND ($2='' OR ($2='active' AND i.status<>'RESOLVED') OR i.status=$2) AND ($3='' OR a.asset_id=$3) ORDER BY (i.priority='CRITICAL') DESC,i.updated_at DESC LIMIT 200`,[q,status,assetId])).rows);}
export async function getIncident(id:string){parse(uuidSchema,id);const incident=(await query<Incident>(`SELECT ${incidentProjection} ${incidentFrom} WHERE i.id=$1`,[id])).rows[0];if(!incident)throw new AppError(404,'Nie znaleziono zgłoszenia.');const history=(await query<History>(`SELECT e.id,e.action,e.description,e.created_at AS "createdAt",u.name AS "actorName",e.before_data AS before,e.after_data AS after FROM audit_logs e LEFT JOIN users u ON u.id=e.actor_id WHERE e.entity_type='incident' AND e.entity_id=$1 ORDER BY e.created_at DESC LIMIT 100`,[id])).rows;return clean({incident,history});}
export async function incidentOperators(){return (await query('SELECT id,name FROM users WHERE active AND role<>\'VIEWER\' ORDER BY name')).rows;}
export async function saveIncident(id:string|null,body:unknown,user:User){requirePermission(user,'incident.edit');if(id)parse(uuidSchema,id);const input=parse(z.object({title:z.string().trim().min(3).max(200),description:z.string().trim().max(10000).default(''),assetId:z.string().regex(/^ITHW-\d{8}$/).nullable().optional(),assignedTo:uuidSchema.nullable().optional(),status:z.enum(['OPEN','ASSIGNED','WAITING','RESOLVED']).default('OPEN'),priority:z.enum(['LOW','NORMAL','HIGH','CRITICAL']).default('NORMAL'),externalReference:z.string().trim().max(160).default(''),version:z.number().int().positive().optional(),requestId:uuidSchema}).strict(),body);
 const incidentId=await transaction(client=>idempotent(client,user,input.requestId,'SAVE_INCIDENT',{id,input},async()=>{
  const before=id?(await client.query('SELECT * FROM incidents WHERE id=$1 FOR UPDATE',[id])).rows[0]:null;if(id&&!before)throw new AppError(404,'Nie znaleziono zgłoszenia.');if(id&&before.version!==input.version)throw new AppError(409,'Zgłoszenie zmieniło się. Odśwież dane.');
  const asset=input.assetId?(await client.query('SELECT id FROM assets WHERE asset_id=$1',[input.assetId])).rows[0]:null;if(input.assetId&&!asset)throw new AppError(400,'Nie znaleziono wskazanego urządzenia.');if(input.assignedTo&&!(await client.query("SELECT id FROM users WHERE id=$1 AND active AND role<>'VIEWER'",[input.assignedTo])).rowCount)throw new AppError(400,'Wybierz aktywnego operatora IT.');
  const params=[input.title,input.description,asset?.id??null,input.assignedTo??null,input.status,input.priority,input.externalReference||null];
  const number=`ITH-${new Date().getFullYear()}-${randomUUID().slice(0,8).toUpperCase()}`;
  const saved=id?(await client.query<{id:string}>('UPDATE incidents SET title=$1,description=$2,asset_id=$3,assigned_to=$4,status=$5,priority=$6,external_reference=$7,version=version+1,updated_at=now() WHERE id=$8 RETURNING id',[...params,id])).rows[0]:(await client.query<{id:string}>('INSERT INTO incidents(title,description,asset_id,assigned_to,status,priority,external_reference,number,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[...params,number,user.id])).rows[0];
  const after={title:input.title,status:input.status,priority:input.priority,assetId:input.assetId??null,assignedTo:input.assignedTo??null};await client.query("INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,description,before_data,after_data) VALUES($1,$2,'incident',$3,$4,$5,$6)",[user.id,id?'UPDATE_INCIDENT':'CREATE_INCIDENT',saved.id,`${id?'Zmieniono':'Utworzono'} zgłoszenie: ${input.title}.`,before?JSON.stringify({title:before.title,status:before.status,priority:before.priority,assignedTo:before.assigned_to}):null,JSON.stringify(after)]);
  if(asset)await client.query("INSERT INTO asset_history(asset_id,actor_id,action,description,after_data) VALUES($1,$2,'SERVICE',$3,$4)",[asset.id,user.id,`Zgłoszenie serwisowe: ${input.title}.`,JSON.stringify({incidentId:saved.id,status:input.status})]);return saved.id;
 }));return getIncident(incidentId);
}
export async function operationsSummary(user:User):Promise<OperationsSummary>{
 const [incidents,inventory,locations,configs,shortages]=await Promise.all([hasPermission(user,'incident.view')?query<{open:number;critical:number}>("SELECT count(*) FILTER(WHERE status<>'RESOLVED')::int AS open,count(*) FILTER(WHERE status<>'RESOLVED' AND priority='CRITICAL')::int AS critical FROM incidents"):Promise.resolve({rows:[{open:0,critical:0}]}),hasPermission(user,'inventory.run')?query<{count:number}>("SELECT count(*)::int AS count FROM inventory_scans WHERE status='OPEN'"):Promise.resolve({rows:[{count:0}]}),hasPermission(user,'location.manage')?query<{count:number}>('SELECT count(*)::int AS count FROM locations'):Promise.resolve({rows:[{count:0}]}),hasPermission(user,'config.view')?query<{count:number}>('SELECT count(*)::int AS count FROM configurations'):Promise.resolve({rows:[{count:0}]}),hasPermission(user,'inventory.view')?query<{count:number}>('SELECT count(*)::int AS count FROM inventory_items WHERE stock<=minimal_stock'):Promise.resolve({rows:[{count:0}]})]);return clean({lowStockCount:shortages.rows[0].count,openIncidents:incidents.rows[0].open,criticalIncidents:incidents.rows[0].critical,openInventory:inventory.rows[0].count,locationCount:locations.rows[0].count,configurationCount:configs.rows[0].count,recentIncidents:hasPermission(user,'incident.view')?(await listIncidents(new URLSearchParams('status=active'))).slice(0,5):[]});
}
export async function locationDetail(id:string,user:User):Promise<LocationDetail>{parse(uuidSchema,id);const location=(await query<Location>('SELECT id,name,path,kind,parent_id AS "parentId",version,asset_count AS "assetCount",child_count AS "childCount" FROM location_summary WHERE id=$1',[id])).rows[0];if(!location)throw new AppError(404,'Nie znaleziono lokalizacji.');const children=(await query<Location>('SELECT id,name,path,kind,parent_id AS "parentId",version,asset_count AS "assetCount",child_count AS "childCount" FROM location_summary WHERE parent_id=$1 ORDER BY name',[id])).rows;
 if(!hasPermission(user,'asset.view'))for(const l of [location,...children])delete l.assetCount;
 const assets=hasPermission(user,'asset.view')?(await query<Asset>(`WITH RECURSIVE branch AS (SELECT id FROM locations WHERE id=$1 UNION ALL SELECT l.id FROM locations l JOIN branch b ON l.parent_id=b.id) SELECT ${assetProjection} ${assetFrom} WHERE a.location_id IN (SELECT id FROM branch) ORDER BY a.updated_at DESC LIMIT 25`,[id])).rows:[];
 const activity=hasPermission(user,'asset.history')?(await query<History>(`WITH RECURSIVE branch AS (SELECT id FROM locations WHERE id=$1 UNION ALL SELECT l.id FROM locations l JOIN branch b ON l.parent_id=b.id) SELECT e.id,e.action,e.description,e.created_at AS "createdAt",u.name AS "actorName" FROM audit_logs e LEFT JOIN users u ON u.id=e.actor_id WHERE (e.entity_type='location' AND e.entity_id::text IN (SELECT id::text FROM branch)) OR ($2 AND e.entity_type='asset' AND (e.before_data->>'locationId' IN (SELECT id::text FROM branch) OR e.after_data->>'locationId' IN (SELECT id::text FROM branch))) ORDER BY e.created_at DESC LIMIT 10`,[id,hasPermission(user,'asset.view')])).rows:[];return clean({location,children,assets,activity});}
function safeServiceUrl(raw:string|null|undefined){if(!raw)return null;try{const url=new URL(raw);if(url.protocol==='https:'&&!url.username&&!url.password&&!url.search&&!url.hash)return url.toString();}catch{}return null;}
export async function getSystemSettings():Promise<SystemSettings>{const setting=(await query<{value:string|null;version:number}>("SELECT value,version FROM system_settings WHERE key='servicenow_url'")).rows[0];return {serviceNowUrl:safeServiceUrl(setting?setting.value:process.env.SERVICENOW_URL),version:setting?.version??0,appUrl:process.env.APP_URL??'',integrationMode:'link'};}
export async function saveSystemSettings(body:unknown,user:User){requirePermission(user,'settings.manage');const input=parse(z.object({serviceNowUrl:z.string().trim().max(2048).nullable(),version:z.number().int().nonnegative()}).strict(),body);const url=safeServiceUrl(input.serviceNowUrl);if(input.serviceNowUrl&&!url)throw new AppError(400,'Podaj URL HTTPS portalu bez danych logowania, parametrów i fragmentu.');await transaction(async client=>{await client.query('SELECT pg_advisory_xact_lock(78491561)');const before=(await client.query("SELECT value,version FROM system_settings WHERE key='servicenow_url' FOR UPDATE")).rows[0];if((before?.version??0)!==input.version)throw new AppError(409,'Ustawienia zmieniły się. Odśwież formularz.');await client.query("INSERT INTO system_settings(key,value,version,updated_by) VALUES('servicenow_url',$1,1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,version=system_settings.version+1,updated_by=EXCLUDED.updated_by,updated_at=now()",[JSON.stringify(url),user.id]);await client.query("INSERT INTO audit_logs(actor_id,action,entity_type,description,before_data,after_data) VALUES($1,'UPDATE_SETTINGS','settings','Zmieniono adres portalu ServiceNow.',$2,$3)",[user.id,JSON.stringify({serviceNowUrl:before?.value??null}),JSON.stringify({serviceNowUrl:url})]);});return getSystemSettings();}
export async function bulkAssets(body:unknown,user:User){const input=parse(z.object({action:z.enum(['move','assign','status']),items:z.array(z.object({assetId:assetIdSchema,version:z.number().int().positive()}).strict()).min(1).max(100),locationId:uuidSchema.optional(),employeeId:uuidSchema.optional(),status:z.enum(['AVAILABLE','ASSIGNED','DAMAGED','REPAIR','PREPARATION','DISPOSAL','RETIRED']).optional(),note:z.string().trim().max(1000).default(''),requestId:uuidSchema}).strict(),body);requirePermission(user,actionPermission[input.action]);if(new Set(input.items.map(i=>i.assetId)).size!==input.items.length)throw new AppError(400,'Lista zawiera powtórzone urządzenia.');
 return transaction(client=>idempotent(client,user,input.requestId,'BULK_ASSETS',input,async()=>{const assets:Asset[]=[];let changed=0;for(const item of [...input.items].sort((a,b)=>a.assetId.localeCompare(b.assetId))){const current=(await client.query<Asset>(`SELECT ${assetProjection} ${assetFrom} WHERE a.asset_id=$1 FOR UPDATE OF a`,[item.assetId])).rows[0];if(!current)throw new AppError(404,`Nie znaleziono ${item.assetId}.`);if(current.version!==item.version)throw new AppError(409,`${item.assetId} zmienił się. Odśwież zaznaczenie.`);const same=input.action==='move'&&input.locationId===current.locationId||input.action==='status'&&input.status===current.status||input.action==='assign'&&input.employeeId===current.employeeId;if(same){assets.push(current);continue;}const body={action:input.action,version:item.version,note:input.note,...(input.action==='move'?{locationId:input.locationId}:input.action==='assign'?{employeeId:input.employeeId}:{status:input.status})};assets.push(await performAssetAction(item.assetId,body,user,client));changed++;}return clean({assets,changed});}));
}
export async function exportSelectedAssets(ids:string[],user:User){requirePermission(user,'asset.export');if(!ids.length||ids.length>100)throw new AppError(400,'Wybierz od 1 do 100 urządzeń.');ids.forEach(id=>parse(assetIdSchema,id));const assets=(await query<Asset>(`SELECT ${assetProjection} ${assetFrom} WHERE a.asset_id=ANY($1::text[]) ORDER BY a.asset_id`,[ids])).rows;return csv([['Asset ID','Nazwa','Model','Numer seryjny','Lokalizacja','Odbiorca','Status'],...assets.map(a=>[a.assetId,a.name,a.model,a.serialNumber,a.locationName,a.owner,a.status])]);}
