import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
test('Purchase entry: exact positions, serial matching, pending documents and opening stock',{skip:!process.env.TEST_DATABASE_URL},async t=>{
 const url=process.env.TEST_DATABASE_URL!;assert.ok(new URL(url).pathname.endsWith('_test'));assert.notEqual(url,process.env.DATABASE_URL);process.env.DATABASE_URL=url;process.env.APP_URL='http://localhost:3000';Object.assign(process.env,{NODE_ENV:'test'});
 const {NextRequest}=await import('next/server'),route=await import('../src/app/api/[...path]/route'),{query,pool}=await import('../src/server/db'),{hashPassword}=await import('../src/server/passwords');
 const tag=randomUUID().slice(0,8),sessions:Record<string,{cookie:string;csrf:string}>={};
 async function call(method:'GET'|'POST'|'PATCH',path:string,body?:unknown,role='ADMIN',csrf=true){const session=sessions[role],headers:Record<string,string>={origin:'http://localhost:3000','content-type':'application/json'};if(session){headers.cookie=session.cookie;if(csrf)headers['x-csrf-token']=session.csrf;}const request=new NextRequest('http://localhost:3000/api/'+path,{method,headers,...(body===undefined?{}:{body:JSON.stringify(body)})});return route[method](request,{params:Promise.resolve({path:path.split('?')[0].split('/')})});}
 async function data(r:Response){const j=await r.json();assert.ok(r.ok,JSON.stringify(j));return j.data;}
 try{
  for(const role of ['ADMIN','VIEWER']){const email=`purchase-${role.toLowerCase()}-${tag}@test.invalid`,password='Fictional purchase tests only!';await query('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4)',['Synthetic purchase '+role,email,await hashPassword(password),role]);const r=await call('POST','auth/login',{email,password});const d=await data(r);sessions[role]={cookie:r.headers.get('set-cookie')!.split(';')[0],csrf:d.csrfToken};}
  const supplier=await data(await call('POST','admin/suppliers',{name:'Synthetic purchase supplier '+tag})),category=(await data(await call('GET','lookups'))).categories[0],location=await data(await call('POST','admin/locations',{name:'Synthetic purchase room '+tag}));
  const existing=await data(await call('POST','assets',{name:'Existing synthetic laptop',categoryId:category.id,serialNumber:'EXIST-'+tag,locationId:location.id,status:'ASSIGNED',owner:'Synthetic operator',purchasePrice:'99.00',purchasedAt:'2026-01-01'}));
  let product:any,invoice:any;
  await t.test('opening stock creates one counted ledger even with concurrent replay',async()=>{
   const body={name:'Synthetic opening cable',slug:'opening-'+tag,category:'Kable i przewody',unit:'m',openingStock:15,openingNote:'Synthetic counted start',requestId:randomUUID()};
   const results=await Promise.all([call('POST','inventory',body),call('POST','inventory',body)]);product=await data(results[0]);assert.equal((await data(results[1])).id,product.id);assert.equal(product.stock,15);const history=await data(await call('GET','inventory/'+product.slug+'/history'));assert.equal(history.length,1);assert.equal(history[0].delta,15);assert.equal((await call('POST','inventory',{...body,openingStock:20})).status,409);assert.equal((await call('POST','inventory',{...body,requestId:randomUUID(),slug:'bad-opening-'+tag,openingNote:''})).status,400);
  });
  await t.test('preview requires access and save requires a fresh explicit match',async()=>{
   const body={serialNumbers:['EXIST-'+tag,'NEW-'+tag]};assert.equal((await call('POST','invoices/serial-preview',body,'NONE')).status,401);assert.equal((await call('POST','invoices/serial-preview',body,'VIEWER')).status,403);assert.equal((await call('POST','invoices/serial-preview',body,'ADMIN',false)).status,403);const p=await data(await call('POST','invoices/serial-preview',body));assert.deepEqual(p.map((v:any)=>v.state),['existing','new']);assert.equal(p[0].assetId,existing.assetId);
   assert.equal((await call('POST','invoices',{number:'UNCONFIRMED-'+tag,supplierId:supplier.id,date:'2026-10-08',items:[{kind:'asset',name:'HP document name',categoryId:category.id,quantity:1,serialNumbers:['EXIST-'+tag]}]})).status,409);assert.equal((await query('SELECT id FROM invoices WHERE number=$1',['UNCONFIRMED-'+tag])).rowCount,0);
  });
  await t.test('mixed receipt preserves document order, raw names and existing equipment',async()=>{
   const body={number:'MIXED-'+tag,supplierId:supplier.id,date:'2026-10-08',receive:true,requestId:randomUUID(),items:[{kind:'other',name:'Z service first',quantity:1,unitPrice:'1.00'},{kind:'inventory',name:'Invoice cable description',inventoryItemId:product.id,quantity:2,unitPrice:null},{kind:'asset',name:'HP document description',categoryId:category.id,quantity:2,unitPrice:null,serialNumbers:['EXIST-'+tag,'NEW-'+tag],matches:[{serialNumber:'EXIST-'+tag,assetId:existing.assetId,version:existing.version}]}]};
   const saved=await data(await call('POST','invoices',body));assert.equal(saved.amount,null);invoice=await data(await call('GET','invoices/'+saved.id));assert.deepEqual(invoice.items.map((l:any)=>l.position),[1,2,3]);assert.deepEqual(invoice.items.map((l:any)=>l.name),['Z service first','Invoice cable description','HP document description']);assert.equal(invoice.items[1].unit,'m');assert.equal(invoice.items[1].inventoryItemName,product.name);assert.equal(invoice.items[1].inventoryItemSlug,product.slug);assert.equal(invoice.assets.length,2);const after=await data(await call('GET','assets/'+existing.assetId));assert.equal(after.status,'ASSIGNED');assert.equal(after.owner,existing.owner);assert.equal(after.locationId,existing.locationId);assert.equal(after.purchasePrice,'99.00');assert.equal(after.purchasedAt,'2026-01-01');assert.equal(after.invoiceItemPosition,3);assert.equal(after.invoiceItemName,'HP document description');assert.equal(invoice.assets.find((a:any)=>a.serialNumber==='NEW-'+tag).purchasePrice,null);assert.equal(invoice.deliveries[0].itemCount,3,'2 cable units plus only 1 new laptop');assert.equal((await data(await call('GET','inventory/'+product.slug))).stock,17);
   assert.equal((await data(await call('POST','invoices',body))).id,saved.id);assert.equal((await data(await call('GET','inventory/'+product.slug))).stock,17);const report=await data(await call('GET','reports'));const group=report.bySupplier.find((g:any)=>g.id===supplier.id);assert.equal(group.unpriced,1);assert.equal(group.value,'99.00');
  });
  await t.test('draft document later links and creates exact serials once',async()=>{
   const draft=await data(await call('POST','invoices',{number:'PENDING-'+tag,supplierId:supplier.id,date:'2026-10-08',items:[{kind:'asset',name:'Pending synthetic HP',categoryId:category.id,quantity:2,serialNumbers:['LATER-1-'+tag]}]}));let d=await data(await call('GET','invoices/'+draft.id));assert.equal(d.assets.length,0);assert.equal(d.amount,null);const line=d.items[0],path=`invoices/${draft.id}/items/${line.id}/serials`,body={serialNumbers:['LATER-1-'+tag],createMissing:true,version:d.version,requestId:randomUUID()};assert.equal((await data(await call('POST',path,body))).created,1);assert.equal((await data(await call('POST',path,body))).created,1);d=await data(await call('GET','invoices/'+draft.id));assert.equal(d.assets.length,1);assert.equal((await call('POST',path,{...body,requestId:randomUUID()})).status,409);await data(await call('POST',path,{serialNumbers:['LATER-2-'+tag],createMissing:true,version:d.version,requestId:randomUUID()}));d=await data(await call('GET','invoices/'+draft.id));assert.equal(d.assets.length,2);assert.equal(d.deliveries[0].itemCount,2);assert.equal(d.items[0].assetIds.length,2);assert.equal((await call('POST',path,{serialNumbers:['EXTRA-'+tag],createMissing:true,version:d.version,requestId:randomUUID()})).status,400);
  });
  await t.test('price completion changes only document prices and rejects stale or foreign positions',async()=>{
   const d=await data(await call('GET','invoices/'+invoice.id)),line=d.items[1],deviceLine=d.items[2],body={number:d.number,supplierId:d.supplierId,date:d.date,currency:d.currency,version:d.version,amount:null,itemPrices:[{id:line.id,unitPrice:'1.99'}]};
   assert.equal((await call('PATCH','invoices/'+d.id,body,'VIEWER')).status,403);assert.equal((await call('PATCH','invoices/'+d.id,body,'ADMIN',false)).status,403);
   assert.equal((await call('PATCH','invoices/'+d.id,{...body,itemPrices:[{id:randomUUID(),unitPrice:'2.00'}]})).status,400);
   const partial=await data(await call('PATCH','invoices/'+d.id,body));assert.equal(partial.amount,null);assert.equal((await call('PATCH','invoices/'+d.id,body)).status,409);
   const complete=await data(await call('PATCH','invoices/'+d.id,{...body,version:partial.version,itemPrices:[{id:deviceLine.id,unitPrice:'123.45'}]}));assert.equal(complete.amount,'251.88');
   const after=await data(await call('GET','invoices/'+d.id));assert.deepEqual(after.items.map((l:any)=>l.id),d.items.map((l:any)=>l.id));assert.equal(after.items[1].unitPrice,'1.99');assert.equal(after.deliveries[0].itemCount,3);assert.equal((await data(await call('GET','inventory/'+product.slug))).stock,17);assert.equal((await data(await call('GET','assets/'+existing.assetId))).purchasePrice,'99.00');assert.equal(after.assets.find((a:any)=>a.serialNumber==='NEW-'+tag).purchasePrice,null);
   assert.equal((await call('PATCH','invoices/'+d.id,{...body,version:complete.version,amount:'1.00',itemPrices:[{id:line.id,unitPrice:'2.00'}]})).status,400);assert.equal((await data(await call('GET','invoices/'+d.id))).items[1].unitPrice,'1.99');
  });
  await t.test('partial receipt can be completed without unnumbered duplicates and currency mismatch rolls back',async()=>{
   const draft=await data(await call('POST','invoices',{number:'PARTIAL-RECEIVE-'+tag,supplierId:supplier.id,date:'2026-10-08',receive:true,items:[{kind:'asset',name:'Partial synthetic HP',categoryId:category.id,quantity:2,serialNumbers:['PARTIAL-1-'+tag]}]}));let d=await data(await call('GET','invoices/'+draft.id));assert.equal(d.assets.length,1);assert.equal(d.deliveries[0].itemCount,1);
   await data(await call('POST',`invoices/${d.id}/items/${d.items[0].id}/serials`,{serialNumbers:['PARTIAL-2-'+tag],createMissing:true,version:d.version,requestId:randomUUID()}));d=await data(await call('GET','invoices/'+draft.id));assert.equal(d.assets.length,2);assert.equal(d.deliveries[0].itemCount,2);assert.ok(d.assets.every((a:any)=>a.serialNumber));
   const card=await data(await call('POST','assets',{name:'Synthetic currency card',categoryId:category.id,serialNumber:'CURRENCY-'+tag,purchasePrice:'10.00'}));assert.equal(card.purchaseCurrency,'PLN');
   assert.equal((await call('POST','invoices',{number:'CURRENCY-CONFLICT-'+tag,supplierId:supplier.id,date:'2026-10-08',currency:'EUR',items:[{kind:'asset',name:'Currency mismatch',categoryId:category.id,quantity:1,serialNumbers:[card.serialNumber],matches:[{serialNumber:card.serialNumber,assetId:card.assetId,version:card.version}]}]})).status,409);assert.equal((await query('SELECT id FROM invoices WHERE number=$1',['CURRENCY-CONFLICT-'+tag])).rowCount,0);assert.equal((await data(await call('GET','assets/'+card.assetId))).invoiceId,null);
  });
  await t.test('pending stock supports bounded partial receipts and preserves legacy unit snapshots',async()=>{
   const draft=await data(await call('POST','invoices',{number:'PENDING-STOCK-'+tag,supplierId:supplier.id,date:'2026-10-08',items:[{kind:'inventory',name:'Pending invoice cable',inventoryItemId:product.id,quantity:5}]}));let d=await data(await call('GET','invoices/'+draft.id));assert.equal(d.items[0].receivedQuantity,0);const path=`invoices/${d.id}/items/${d.items[0].id}/receive`,body={quantity:2,version:d.version,requestId:randomUUID()};
   assert.equal((await call('POST',path,body,'VIEWER')).status,403);assert.equal((await call('POST',path,body,'ADMIN',false)).status,403);assert.deepEqual(await data(await call('POST',path,body)),{received:2,remaining:3});assert.deepEqual(await data(await call('POST',path,body)),{received:2,remaining:3});assert.equal((await data(await call('GET','inventory/'+product.slug))).stock,19);
   d=await data(await call('GET','invoices/'+draft.id));assert.equal(d.items[0].receivedQuantity,2);assert.equal((await call('POST',path,{...body,quantity:4,version:d.version,requestId:randomUUID()})).status,409);assert.equal((await call('POST',path,{...body,requestId:randomUUID()})).status,409);
   await data(await call('POST',path,{quantity:3,version:d.version,requestId:randomUUID()}));d=await data(await call('GET','invoices/'+draft.id));assert.equal(d.items[0].receivedQuantity,5);assert.equal(d.deliveries[0].itemCount,5);assert.equal((await data(await call('GET','inventory/'+product.slug))).stock,22);assert.equal((await call('POST',path,{quantity:1,version:d.version,requestId:randomUUID()})).status,409);
   const legacy=await data(await call('POST','deliveries',{invoiceNumber:'LEGACY-UNIT-'+tag,supplierId:supplier.id,date:'2026-10-08',requestId:randomUUID(),items:[{kind:'asset',name:'Z legacy device first',categoryId:category.id,quantity:1,unitPrice:'1.00'},{kind:'inventory',inventoryItemId:product.id,quantity:1,unitPrice:'1.00'}]}));const old=await data(await call('GET','invoices/'+legacy.invoiceId));assert.deepEqual(old.items.map((l:any)=>l.position),[1,2]);assert.equal(old.items[0].name,'Z legacy device first');assert.equal(old.items[1].unit,'m');assert.equal(old.items[1].receivedQuantity,1);
  });
  await t.test('serial conflicts and concurrent invoices cannot duplicate or reassign a card',async()=>{
   const p=await data(await call('POST','invoices/serial-preview',{serialNumbers:['EXIST-'+tag]}));assert.equal(p[0].state,'conflict');const bad={number:'CONFLICT-'+tag,supplierId:supplier.id,date:'2026-10-08',receive:true,items:[{kind:'asset',name:'Bad',categoryId:category.id,quantity:1,serialNumbers:['EXIST-'+tag]}]};assert.equal((await call('POST','invoices',bad)).status,409);
   const results=await Promise.all([0,1].map(i=>call('POST','invoices',{...bad,number:`RACE-${i}-${tag}`,requestId:randomUUID(),items:[{kind:'asset',name:'Synthetic race card',categoryId:category.id,quantity:1,serialNumbers:['RACE-SN-'+tag]}]})));assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);assert.equal((await query('SELECT id FROM assets WHERE serial_number=$1',['RACE-SN-'+tag])).rowCount,1);assert.equal((await query('SELECT id FROM invoices WHERE number=ANY($1::text[])',[[`RACE-0-${tag}`,`RACE-1-${tag}`]])).rowCount,1);
  });
 }finally{await pool.end();}
});
