import type {EquipmentDocument} from './types';
import {statusLabels} from './types';
export const documentTitles={equipment:'Karta wyposażenia pracownika',clearance:'Obiegówka — rozliczenie sprzętu IT',workstation:'Karta wyposażenia stanowiska'};
export const escapeHtml=(value:unknown)=>String(value??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function equipmentDocumentHtml(doc:EquipmentDocument):string{
 const e=escapeHtml,s=doc.snapshot.subject,clearance=doc.kind==='clearance';
 const rows=doc.snapshot.items.map((a,i)=>`<tr><td>${i+1}</td><td><b>${e(a.name)}</b><br>${e(a.model)}</td><td>${e(a.assetId)}</td><td>${e(a.serialNumber)}</td><td>${e(clearance?'':statusLabels[a.status])}</td>${clearance?'<td></td><td></td>':''}</tr>`).join('');
 return `<!doctype html><html lang="pl"><meta charset="utf-8"><title>${e(doc.reference)}</title><style>body{font:12px Arial,sans-serif;color:#111;background:white;margin:28px}h1{font-size:22px;margin:24px 0 8px}.brand{font-size:19px;letter-spacing:1px}small{color:#555}dl{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:22px 0}dt{color:#555;font-size:10px}dd{margin:4px 0}table{border-collapse:collapse;width:100%;font-size:10px}th,td{border:1px solid #bbb;padding:8px;text-align:left;overflow-wrap:anywhere}th{background:#eee}td{height:28px}.notes{white-space:pre-wrap;min-height:50px;margin:20px 0}.signatures{display:flex;justify-content:space-between;gap:28px;margin-top:60px}.signatures div{border-top:1px solid #777;padding-top:8px;width:45%}tr{break-inside:avoid}@page{size:A4;margin:14mm}@media print{body{margin:0}}</style><body><div class="brand">IT HARDWARE</div><small>R O B A K O W O</small><h1>${e(documentTitles[doc.kind])}</h1><p>${e(doc.reference)} · ${e(new Date(doc.createdAt).toLocaleString('pl-PL',{timeZone:'Europe/Warsaw'}))}</p><dl><div><dt>${doc.kind==='workstation'?'Stanowisko':'Pracownik'}</dt><dd>${e(s.name)}</dd></div><div><dt>Numer pracownika / lokalizacja</dt><dd>${e(s.employeeNumber||s.locationName)}</dd></div><div><dt>Dział / stanowisko</dt><dd>${e([s.department,s.position].filter(Boolean).join(' / ')||'—')}</dd></div><div><dt>Dokument przygotował</dt><dd>${e(doc.createdBy)}</dd></div></dl><p>${clearance?'Wypełnić podczas fizycznego rozliczenia. Ten dokument nie potwierdza zwrotu w systemie.':doc.kind==='workstation'?'Wyposażenie przypisane do stanowiska. Nie oznacza osobistego wydania pracownikowi.':'Stan urządzeń przypisanych bezpośrednio do pracownika na dzień zapisu.'}</p><table><thead><tr><th>Lp.</th><th>Urządzenie / model</th><th>Asset ID</th><th>Numer seryjny</th><th>${clearance?'Zwrócono / brak':'Status'}</th>${clearance?'<th>Stan / uwagi</th><th>Data / podpis IT</th>':''}</tr></thead><tbody>${rows||`<tr><td colspan="${clearance?7:5}">Brak przypisanego sprzętu na dzień zapisu.</td></tr>`}</tbody></table><div class="notes"><b>Uwagi:</b><br>${e(doc.snapshot.notes||'........................................................................................................')}</div>${clearance?'<p>□ Sprzęt sprawdzony fizycznie &nbsp; □ Braki opisane &nbsp; □ Zwroty zapisane w ewidencji</p><p>Data rozliczenia: ........................................</p>':''}<div class="signatures"><div>${doc.kind==='workstation'?'Osoba sprawdzająca':'Podpis pracownika'} / data</div><div>Przedstawiciel IT / data</div></div><p><small>Zapis historyczny ${e(doc.reference)}. Późniejsze zmiany ewidencji nie zmieniają tego dokumentu.</small></p></body></html>`;
}
