'use client';
import {useState,type FormEvent} from 'react';
import {Plus,Save,ShieldCheck,Copy,ExternalLink} from 'lucide-react';
import type {Role,User} from '@/shared/types';
import {roleLabels} from '@/shared/types';
import {permissions,permissionGroups,rolePermissions,hasPermission,type Permission} from '@/shared/permissions';
import type {PermissionRole,SystemSettings} from '@/shared/product';
import {useApp} from './context';
import {ThemeSettings} from './theme';
import {api,Button,ErrorMessage,Field,Loading,Modal,PageHeader,SuccessMessage,useResource,formatDate} from './ui';
const actionLabels:Record<string,string>={view:'Przeglądanie',create:'Dodawanie',edit:'Edycja',assign:'Wydawanie / zwroty',move:'Przenoszenie',status:'Zmiana statusu',export:'Eksport',history:'Historia',print:'Druk etykiet',scan:'Skanowanie',delete:'Usuwanie',run:'Inwentaryzacja',download:'Pobieranie',upload:'Dodawanie plików',document:'Dokumenty wyposażenia',manage:'Zarządzanie'};
export function PermissionsScreen(){
 const {user}=useApp(),roles=useResource<PermissionRole[]>('/api/admin/permissions'),users=useResource<User[]>('/api/admin/users');const [editing,setEditing]=useState<PermissionRole|null|undefined>(),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState<string|null>(null);
 async function assign(id:string,roleId:string){setBusy(id);setError('');try{await api('/api/admin/users/'+id+'/access',{method:'PATCH',body:JSON.stringify({roleId:roleId||null})},user.csrfToken);users.reload();setNotice('Zapisano profil dostępu. Dotychczasowe sesje konta zostały zakończone.');}catch(e){setError((e as Error).message);}finally{setBusy(null);}}
 return <><PageHeader eyebrow="ITH // ACCESS CONTROL" title="Role i uprawnienia" description="Role systemowe wyznaczają zakres maksymalny. Profile własne pozwalają ograniczyć wybrane czynności." actions={<Button onClick={()=>setEditing(null)}><Plus size={16}/>Nowy profil</Button>}/><SuccessMessage message={notice}/><ErrorMessage message={roles.error||users.error||error} onRetry={()=>{roles.reload();users.reload();}}/>{roles.loading&&!roles.data?<Loading/>:<><div className="table-wrap permission-matrix"><table className="data-table"><thead><tr><th>Moduł / czynność</th>{(Object.keys(rolePermissions) as Role[]).map(r=><th key={r}>{roleLabels[r]}</th>)}{roles.data?.map(r=><th key={r.id}><button className="text-link" onClick={()=>setEditing(r)}>{r.name} · edytuj</button></th>)}</tr></thead><tbody>{Object.entries(permissionGroups).map(([group,values])=>values.map((p,i)=><tr key={p}><td>{i===0&&<small className="eyebrow">{group}</small>}{actionLabels[p.split('.')[1]]??p}<small className="mono">{p}</small></td>{(Object.keys(rolePermissions) as Role[]).map(r=><td className="permission-cell" key={r} aria-label={rolePermissions[r].includes(p)?'Dozwolone':'Brak dostępu'}>{rolePermissions[r].includes(p)?<ShieldCheck size={16}/>:<span>—</span>}</td>)}{roles.data?.map(r=><td className="permission-cell" key={r.id}>{r.permissions.includes(p)?<ShieldCheck size={16}/>:<span>—</span>}</td>)}</tr>))}</tbody></table></div><section className="access-assignments"><div className="section-heading"><h2>Profile kont</h2><span>Zmiana unieważnia sesje</span></div>{users.data?.map(account=><div className="access-account" key={account.id}><div><strong>{account.name}</strong><small>{account.email} · {roleLabels[account.role]}</small></div><select aria-label={'Profil uprawnień '+account.name} value={account.customRoleId??''} disabled={busy!==null||account.role==='ADMIN'||account.id===user.id} onChange={e=>assign(account.id,e.target.value)}><option value="">Rola systemowa</option>{roles.data?.map(r=><option key={r.id} value={r.id}>{r.name} ({roleLabels[r.baseRole]})</option>)}</select></div>)}</section></>}{editing!==undefined&&<PermissionForm profile={editing} onClose={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);roles.reload();setNotice('Zapisano profil uprawnień.');}}/>}</>;
}
function PermissionForm({profile,onClose,onSaved}:{profile:PermissionRole|null;onClose:()=>void;onSaved:()=>void}){
 const {user}=useApp();const [name,setName]=useState(profile?.name??''),[base,setBase]=useState<Role>(profile?.baseRole??'IT_USER'),[selected,setSelected]=useState<Permission[]>(profile?.permissions??[...rolePermissions.IT_USER]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await api('/api/admin/permissions'+(profile?'/'+profile.id:''),{method:profile?'PATCH':'POST',body:JSON.stringify({name,baseRole:base,permissions:selected,...(profile?{version:profile.version}:{})})},user.csrfToken);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title={profile?'Edytuj profil dostępu':'Nowy profil dostępu'} onClose={()=>{if(!busy)onClose();}}><form onSubmit={submit}><ErrorMessage message={error}/><div className="form-grid"><Field label="Nazwa profilu *"><input required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Rola bazowa"><select disabled={!!profile} value={base} onChange={e=>{const r=e.target.value as Role;setBase(r);setSelected([...rolePermissions[r]]);}}>{(['VIEWER','IT_USER','IT_ADVANCED'] as Role[]).map(r=><option key={r} value={r}>{roleLabels[r]}</option>)}</select></Field></div><div className="permission-editor">{Object.entries(permissionGroups).map(([group,values])=><fieldset key={group}><legend>{group}</legend>{values.map(p=><label className="checkbox-inline" key={p}><input type="checkbox" disabled={!rolePermissions[base].includes(p)} checked={selected.includes(p)} onChange={e=>setSelected(v=>e.target.checked?[...v,p]:v.filter(x=>x!==p))}/><span>{actionLabels[p.split('.')[1]]??p}<small className="mono">{p}</small></span></label>)}</fieldset>)}</div><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Anuluj</Button><Button disabled={busy}><Save size={15}/>{busy?'Zapisywanie…':'Zapisz profil'}</Button></div></form></Modal>;
}
export function InvitationModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){
 const {user}=useApp();const [name,setName]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('IT_USER'),[result,setResult]=useState<{url:string;expiresAt:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{setResult(await api('/api/admin/users/invite',{method:'POST',body:JSON.stringify({name,email,role})},user.csrfToken));onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title="Zaproś użytkownika" onClose={()=>{if(!busy)onClose();}}><ErrorMessage message={error}/>{result?<><p>Zaproszenie dla {name} jest ważne do {formatDate(result.expiresAt,true)}.</p><Field label="Jednorazowy link aktywacji"><input readOnly value={result.url} onFocus={e=>e.target.select()}/></Field><p className="help-note">Przekaż link odbiorcy. Hasło ustawi samodzielnie. Wysyłka e-mail wymaga skonfigurowanej usługi pocztowej.</p><div className="form-actions"><Button variant="secondary" onClick={onClose}>Zamknij</Button><Button onClick={async()=>{try{await navigator.clipboard.writeText(result.url);setCopied(true);}catch{setError('Skopiuj link z pola tekstowego.');}}}><Copy size={15}/>{copied?'Skopiowano':'Kopiuj link'}</Button></div></>:<form onSubmit={submit}><div className="form-grid"><Field label="Imię i nazwisko *"><input required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="E-mail *"><input required type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Rola"><select value={role} onChange={e=>setRole(e.target.value)}>{(['VIEWER','IT_USER','IT_ADVANCED'] as Role[]).map(r=><option key={r} value={r}>{roleLabels[r]}</option>)}</select></Field></div><p className="help-note">Link jest ważny 7 dni i można użyć go raz.</p><div className="form-actions"><Button variant="secondary" type="button" disabled={busy} onClick={onClose}>Anuluj</Button><Button disabled={busy}>{busy?'Tworzenie…':'Utwórz zaproszenie'}</Button></div></form>}</Modal>;
}
export function SettingsScreen(){
 const {user,refreshLookups}=useApp(),resource=useResource<SystemSettings>('/api/admin/settings');const [url,setUrl]=useState<string|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(e:FormEvent){e.preventDefault();if(busy||!resource.data)return;setBusy(true);setError('');try{await api('/api/admin/settings',{method:'PATCH',body:JSON.stringify({serviceNowUrl:(url??resource.data.serviceNowUrl??'').trim()||null,version:resource.data.version})},user.csrfToken);setUrl(null);resource.reload();refreshLookups();setNotice('Zapisano adres portalu.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><PageHeader eyebrow="ITH // SYSTEM" title="Ustawienia systemu" description="Połączenia i słowniki wykorzystywane w codziennej pracy."/><ThemeSettings/><ErrorMessage message={error||resource.error} onRetry={resource.reload}/><SuccessMessage message={notice}/>{resource.loading&&!resource.data?<Loading/>:resource.data&&<form className="settings-form" onSubmit={save}><h2>Portal ServiceNow</h2><p>Łącze do firmowego portalu. Synchronizacja zgłoszeń przez API wymaga adresu instancji, uwierzytelnienia i uzgodnionego zakresu danych.</p><Field label="Adres portalu HTTPS"><input type="url" placeholder="https://firma.service-now.com/" maxLength={2048} value={url??resource.data.serviceNowUrl??''} onChange={e=>setUrl(e.target.value)}/></Field><Button disabled={busy}><Save size={15}/>{busy?'Zapisywanie…':'Zapisz ustawienia'}</Button><dl className="settings-facts"><dt>Adres aplikacji / linki QR</dt><dd className="mono">{resource.data.appUrl}</dd><dt>Tryb integracji ServiceNow</dt><dd>Portal zewnętrzny</dd></dl></form>}<div className="section-heading"><h2>Słowniki</h2></div><div className="settings-links"><a className="button button-secondary" href="/admin?tab=categories">Kategorie sprzętu i pola</a><a className="button button-secondary" href="/admin?tab=suppliers">Kontrahenci</a></div></>;
}
