'use client';
import Link from 'next/link';
import {useState} from 'react';
import type {Asset} from '@/shared/types';
import type {Configuration,ConfigurationDetail,Incident} from '@/shared/product';
import {hasPermission} from '@/shared/permissions';
import {useApp} from './context';
import {api,Button,EmptyState,ErrorMessage,Field,formatDate,Loading,Modal,SuccessMessage,useResource} from './ui';
export interface AssetConfiguration {id:string;configurationId:string;name:string;version:string;appliedAt:string;author:string}
export function AssetConfigurationPanel({asset,onSaved}:{asset:Asset;onSaved:()=>void}){
 const {user}=useApp(),resource=useResource<AssetConfiguration[]>('/api/assets/'+asset.assetId+'/configurations');const [open,setOpen]=useState(false),[notice,setNotice]=useState('');
 return <><div className="panel-heading"><div><h2>Konfiguracje urządzenia</h2><p>Zapisane przypisania wersji. Wdrożenie na sprzęcie wykonuje operator IT.</p></div>{hasPermission(user,'config.edit')&&hasPermission(user,'asset.edit')&&<Button variant="secondary" onClick={()=>setOpen(true)}>Przypisz wersję</Button>}</div><SuccessMessage message={notice}/><ErrorMessage message={resource.error} onRetry={resource.reload}/><div className="asset-config-index">{resource.loading&&!resource.data?<Loading compact/>:resource.data?.length?resource.data.map(c=><Link key={c.id} href={'/configs/'+c.configurationId+'?version='+c.id}><strong>{c.name} · v{c.version}</strong><small>{formatDate(c.appliedAt,true)} · {c.author}</small></Link>):!resource.error&&<EmptyState title="Brak przypisanych konfiguracji" description="Wybierz konkretną wersję z biblioteki, aby zachować informację o konfiguracji urządzenia."/>}</div>{open&&<ApplyConfiguration asset={asset} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);resource.reload();onSaved();setNotice('Zapisano przypisanie wersji konfiguracji.');}}/>}</>;
}
function ApplyConfiguration({asset,onClose,onSaved}:{asset:Asset;onClose:()=>void;onSaved:()=>void}){
 const {user}=useApp(),configs=useResource<Configuration[]>('/api/configs'),[configId,setConfigId]=useState(''),[versionId,setVersionId]=useState(''),detail=useResource<ConfigurationDetail>(configId?'/api/configs/'+configId:null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Modal title="Przypisz wersję konfiguracji" onClose={()=>{if(!busy)onClose();}}><form onSubmit={async e=>{e.preventDefault();if(!detail.data||busy)return;setBusy(true);setError('');try{await api('/api/configs/'+configId+'/apply',{method:'POST',body:JSON.stringify({assetId:asset.id,assetVersion:asset.version,versionId:versionId||detail.data.versions[0]?.id})},user.csrfToken);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><ErrorMessage message={error||configs.error||detail.error}/><Field label="Konfiguracja *"><select required disabled={busy} value={configId} onChange={e=>{setConfigId(e.target.value);setVersionId('');}}><option value="">Wybierz konfigurację</option>{configs.data?.map(c=><option key={c.id} value={c.id}>{c.name} · {c.model}</option>)}</select></Field>{detail.data&&<Field label="Wersja"><select disabled={busy} value={versionId||detail.data.versions[0]?.id||''} onChange={e=>setVersionId(e.target.value)}>{detail.data.versions.map(v=><option key={v.id} value={v.id}>v{v.version} · {formatDate(v.createdAt,true)}</option>)}</select></Field>}<p className="help-note">Potwierdź wersję, którą zastosowano na urządzeniu {asset.assetId}. Zapis dodaje informację do ewidencji i historii urządzenia.</p><div className="form-actions"><Button type="button" variant="secondary" onClick={onClose} disabled={busy}>Anuluj</Button><Button disabled={busy||detail.loading||!configId||!detail.data}>{busy?'Zapisywanie…':'Zapisz przypisanie wersji'}</Button></div></form></Modal>;
}
export function AssetServicePanel({asset}:{asset:Asset}){
 const {user}=useApp(),resource=useResource<Incident[]>('/api/incidents?assetId='+asset.assetId);
 return <><div className="panel-heading"><h2>Serwis urządzenia</h2>{hasPermission(user,'incident.edit')&&<Link href={'/incidents?create=1&assetId='+asset.assetId} className="button button-secondary">Zgłoś usterkę</Link>}</div><ErrorMessage message={resource.error} onRetry={resource.reload}/><div className="asset-service-index">{resource.loading&&!resource.data?<Loading compact/>:resource.data?.length?resource.data.map(i=><Link key={i.id} href={'/incidents/'+i.id}><strong>{i.title}</strong><small>{i.number} · {i.status==='RESOLVED'?'Rozwiązane':'Otwarte'} · {formatDate(i.updatedAt,true)}</small></Link>):!resource.error&&<EmptyState title="Brak zarejestrowanych zgłoszeń" description="Zapisane usterki i naprawy będą widoczne na tej karcie."/>}</div></>;
}
