'use client';
import {createUuid} from '@/shared/uuid';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Download,Printer,Save,X} from 'lucide-react';
import type {Asset,AssetStatus} from '@/shared/types';
import {statuses,statusLabels} from '@/shared/types';
import {hasPermission,type Permission} from '@/shared/permissions';
import {useApp} from './context';
import {ContextMenu,type MenuAction} from './context-menu';
import {ActionModal} from './asset-actions';
import {EmployeePicker,LocationPicker} from './pickers';
import {api,Button,ErrorMessage,Field,Modal,QRLabel,SuccessMessage} from './ui';
type AssetAction='assign'|'return'|'move'|'status'|'rfid'|'note';
export function AssetRecordMenu({asset,onEdit,onSaved}:{asset:Asset;onEdit:()=>void;onSaved:()=>void}){
 const {user}=useApp(),[action,setAction]=useState<AssetAction|null>(null),[label,setLabel]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const items:MenuAction[]=[{label:'Otwórz paszport',href:'/asset/'+asset.assetId},{label:'Kopiuj Asset ID',onClick:async()=>{setNotice('');setError('');try{await navigator.clipboard.writeText(asset.assetId);setNotice('Skopiowano Asset ID.');}catch{setError('Nie udało się skopiować identyfikatora.');}}}];
 if(hasPermission(user,'asset.edit'))items.push({label:'Edytuj urządzenie',onClick:onEdit});
 if(hasPermission(user,'asset.history'))items.push({label:'Historia urządzenia',href:'/asset/'+asset.assetId+'#passport-history'});
 for(const [act,text,permission] of [['assign',asset.owner?'Przekaż urządzenie':'Wydaj urządzenie','asset.assign'],['return','Przyjmij zwrot','asset.assign'],['move','Przenieś do lokalizacji','asset.move'],['status','Zmień status','asset.status'],['rfid','Przypisz / odłącz RFID','rfid.edit']] as [AssetAction,string,Permission][])if(hasPermission(user,permission))items.push({label:text,onClick:()=>setAction(act),disabled:act==='assign'&&!['AVAILABLE','PREPARATION','ASSIGNED'].includes(asset.status)||act==='return'&&!asset.owner});
 if(hasPermission(user,'document.view'))items.push({label:'Pliki urządzenia',href:'/asset/'+asset.assetId+'#passport-files'});
 if(hasPermission(user,'label.print'))items.push({label:'Etykieta QR / druk',onClick:()=>setLabel(true)});
 return <><ContextMenu label={'Akcje urządzenia '+asset.name} items={items}/><SuccessMessage message={notice}/><ErrorMessage message={error}/>{action&&<ActionModal key={action} asset={asset} action={action} onClose={()=>setAction(null)} onSaved={()=>{setAction(null);onSaved();}}/>}{label&&<Modal title={'Etykieta '+asset.assetId} onClose={()=>setLabel(false)}><QRLabel type="asset" id={asset.assetId} name={asset.name}/></Modal>}</>;
}
export function BulkAssetToolbar({selected,onClear,onSaved}:{selected:Record<string,Asset>;onClear:()=>void;onSaved:(message:string)=>void}){
 const {user}=useApp(),assets=Object.values(selected),[action,setAction]=useState<'move'|'assign'|'status'|null>(null),[labels,setLabels]=useState(false);
 if(!assets.length)return null;
 return <><div className="bulk-toolbar"><strong>Zaznaczono {assets.length} / 100</strong>{hasPermission(user,'asset.move')&&<Button variant="secondary" onClick={()=>setAction('move')}>Przenieś</Button>}{hasPermission(user,'asset.status')&&<Button variant="secondary" onClick={()=>setAction('status')}>Status</Button>}{hasPermission(user,'asset.assign')&&<Button variant="secondary" onClick={()=>setAction('assign')}>Wydaj / przekaż</Button>}{hasPermission(user,'asset.export')&&<a className="button button-secondary" download href={'/api/assets/selection.csv?ids='+assets.map(a=>a.assetId).join(',')}><Download size={14}/>CSV</a>}{hasPermission(user,'label.print')&&<Button variant="secondary" onClick={()=>setLabels(true)}><Printer size={14}/>Etykiety</Button>}<Button variant="ghost" onClick={onClear} aria-label="Wyczyść zaznaczenie"><X size={15}/></Button></div>{action&&<BulkForm key={action} assets={assets} action={action} onClose={()=>setAction(null)} onSaved={changed=>{setAction(null);onClear();onSaved('Zapisano zmiany dla '+changed+' urządzeń.');}}/>}{labels&&<BulkLabels assets={assets} onClose={()=>setLabels(false)}/>}</>;
}
function BulkForm({assets,action,onClose,onSaved}:{assets:Asset[];action:'move'|'assign'|'status';onClose:()=>void;onSaved:(changed:number)=>void}){
 const {user}=useApp(),[locationId,setLocationId]=useState(''),[employeeId,setEmployeeId]=useState(''),[status,setStatus]=useState<AssetStatus>('AVAILABLE'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),pending=useRef<{signature:string;id:string}|null>(null);
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const body={action,items:assets.map(a=>({assetId:a.assetId,version:a.version})),note,...(action==='move'?{locationId}:action==='assign'?{employeeId}:{status})},signature=JSON.stringify(body);if(pending.current?.signature!==signature)pending.current={signature,id:createUuid()};const value=await api<{changed:number}>('/api/assets/bulk',{method:'POST',body:JSON.stringify({...body,requestId:pending.current.id})},user.csrfToken);onSaved(value.changed);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title={({move:'Przenieś urządzenia',assign:'Wydaj / przekaż urządzenia',status:'Zmień status urządzeń'})[action]} onClose={()=>{if(!busy)onClose();}}><form onSubmit={submit}><p className="help-note">Zaznaczono {assets.length} urządzeń. Zmiany zapisują się razem. Jeśli jeden rekord zmienił się lub nie może zostać zmieniony, cała operacja zostanie anulowana.</p><ErrorMessage message={error}/>{action==='move'?<LocationPicker label="Nowa lokalizacja *" required disabled={busy} value={locationId} onChange={setLocationId}/>:action==='assign'?<EmployeePicker label="Nowy odbiorca *" required disabled={busy} employeeId={employeeId} owner="" onChange={setEmployeeId}/>:<Field label="Nowy status"><select disabled={busy} value={status} onChange={e=>setStatus(e.target.value as AssetStatus)}>{statuses.filter(s=>s!=='ASSIGNED').map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></Field>}<Field label="Powód / uwagi"><textarea maxLength={1000} disabled={busy} value={note} onChange={e=>setNote(e.target.value)}/></Field><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Anuluj</Button><Button disabled={busy||action==='move'&&!locationId||action==='assign'&&!employeeId}>{busy?'Zapisywanie…':'Zapisz dla '+assets.length+' urządzeń'}</Button></div></form></Modal>;
}
function BulkLabels({assets,onClose}:{assets:Asset[];onClose:()=>void}){
 const preview=useRef<HTMLDivElement>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function print(){if(!preview.current||busy)return;setBusy(true);setError('');let sheet:HTMLDivElement|null=null;try{await Promise.all(Array.from(preview.current.querySelectorAll('img')).map(i=>i.decode()));document.querySelector('.print-only')?.remove();sheet=document.createElement('div');sheet.className='print-only bulk-label-print';sheet.appendChild(preview.current.cloneNode(true));const style=document.createElement('style');style.textContent='@media print{@page{size:60mm 50mm;margin:0}.bulk-label-grid{display:block!important}.bulk-label-item{width:60mm;height:50mm;box-sizing:border-box;break-after:page;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:2mm;color:#000;background:#fff}.bulk-label-item:last-child{break-after:auto}.bulk-label-item img{width:32mm;height:32mm}.bulk-label-item strong{font:8pt Arial}.bulk-label-item span{font:7pt monospace}}';sheet.appendChild(style);document.body.appendChild(sheet);const printed=sheet;window.addEventListener('afterprint',()=>printed.remove(),{once:true});window.print();}catch{sheet?.remove();setError('Nie udało się wczytać wszystkich QR. Spróbuj ponownie.');}finally{setBusy(false);}}
 return <Modal wide title={'Etykiety QR · '+assets.length+' urządzeń'} onClose={onClose}><p className="help-note">Etykieta 60 × 50 mm. W podglądzie wydruku wybierz ten rozmiar papieru oraz skalę 100%. Sprawdź pierwszą etykietę na drukarce.</p><ErrorMessage message={error}/><div className="bulk-label-grid" ref={preview}>{assets.map(a=><div className="bulk-label-item" key={a.id}><img src={'/api/qr?type=asset&id='+a.assetId} alt={'QR '+a.assetId} width={120} height={120}/><strong>{a.name}</strong><span>{a.assetId}</span></div>)}</div><div className="form-actions"><Button variant="secondary" onClick={onClose}>Zamknij</Button><Button disabled={busy} onClick={print}><Printer size={15}/>{busy?'Przygotowywanie…':'Drukuj etykiety'}</Button></div></Modal>;
}
export function AssetViews({value,onApply}:{value:{q:string;filters:Record<string,string>;columns:Record<string,boolean>};onApply:(view:typeof value)=>void}){
 const {user}=useApp(),key='ith-asset-views:'+user.id;const [views,setViews]=useState<(typeof value&{name:string})[]>([]),[open,setOpen]=useState(false),[name,setName]=useState(''),[selected,setSelected]=useState('');
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(v))setViews(v.filter(x=>x&&typeof x.name==='string'&&typeof x.q==='string'&&x.filters&&x.columns).slice(0,8));}catch{}},[key]);
 function store(next:typeof views){setViews(next);try{localStorage.setItem(key,JSON.stringify(next));}catch{}}
 return <><div className="asset-views"><select aria-label="Zapisany widok urządzeń" value={selected} onChange={e=>{setSelected(e.target.value);const v=views.find(v=>v.name===e.target.value);if(v)onApply(v);}}><option value="">Moje widoki</option>{views.map(v=><option key={v.name} value={v.name}>{v.name}</option>)}</select><Button variant="ghost" onClick={()=>setOpen(true)} aria-label="Zapisz bieżący widok"><Save size={15}/></Button>{selected&&<Button variant="ghost" onClick={()=>{store(views.filter(v=>v.name!==selected));setSelected('');}} aria-label="Usuń zapisany widok"><X size={14}/></Button>}</div>{open&&<Modal title="Zapisz widok tabeli" onClose={()=>setOpen(false)}><form onSubmit={e=>{e.preventDefault();const label=name.trim();if(!label)return;store([{...value,name:label},...views.filter(v=>v.name!==label)].slice(0,8));setSelected(label);setOpen(false);}}><Field label="Nazwa widoku"><input autoFocus required maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="np. Monitory · Office"/></Field><p className="help-note">Zapamiętamy filtry, sortowanie i kolumny w tej przeglądarce dla Twojego konta. Do 8 widoków.</p><div className="form-actions"><Button variant="secondary" type="button" onClick={()=>setOpen(false)}>Anuluj</Button><Button>Zapisz widok</Button></div></form></Modal>}</>;
}
