'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {MoreHorizontal} from 'lucide-react';
export interface MenuAction {label:string;href?:string;onClick?:()=>void;disabled?:boolean;danger?:boolean}
export function ContextMenu({items,label='Otwórz menu',children,className='icon-button'}:{items:MenuAction[];label?:string;children?:React.ReactNode;className?:string}){
 const [anchor,setAnchor]=useState<{x:number;y:number}|null>(null),trigger=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null);const close=()=>setAnchor(null);
 useEffect(()=>{if(!anchor)return;menu.current?.querySelector<HTMLElement>('[role=menuitem]:not([disabled])')?.focus();const outside=(e:PointerEvent)=>{if(!menu.current?.contains(e.target as Node)&&!trigger.current?.contains(e.target as Node))close();};const scroll=(e:Event)=>{if(!menu.current?.contains(e.target as Node))close();};document.addEventListener('pointerdown',outside);window.addEventListener('scroll',scroll,true);window.addEventListener('resize',close);return()=>{document.removeEventListener('pointerdown',outside);window.removeEventListener('scroll',scroll,true);window.removeEventListener('resize',close);};},[anchor]);
 function choose(action:MenuAction){close();trigger.current?.focus();action.onClick?.();}
 return <><button ref={trigger} data-row-menu type="button" className={className} aria-label={label} aria-haspopup="menu" aria-expanded={!!anchor} onClick={e=>{e.stopPropagation();if(anchor){close();return;}const rect=e.currentTarget.getBoundingClientRect();setAnchor({x:Math.max(8,Math.min(rect.right-224,window.innerWidth-232)),y:Math.min(rect.bottom+6,window.innerHeight-items.length*40-26)});}}>{children??<MoreHorizontal size={19}/>}</button>{anchor&&createPortal(<div ref={menu} className="context-menu" role="menu" aria-label={label} style={{left:anchor.x,top:Math.max(8,anchor.y)}} onKeyDown={e=>{const nodes=Array.from(menu.current?.querySelectorAll<HTMLElement>('[role=menuitem]:not([disabled])')??[]),index=nodes.indexOf(document.activeElement as HTMLElement);if(e.key==='Escape'||e.key==='Tab'){close();if(e.key==='Escape'){e.preventDefault();trigger.current?.focus();}}else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?nodes.length-1:(index+(e.key==='ArrowDown'?1:-1)+nodes.length)%nodes.length;nodes[next]?.focus();}}}>{items.map((action,i)=>action.href&&!action.disabled?<Link key={i} role="menuitem" className={action.danger?'text-danger':''} href={action.href} onClick={()=>choose(action)}>{action.label}</Link>:<button key={i} role="menuitem" type="button" disabled={action.disabled} className={action.danger?'text-danger':''} onClick={()=>choose(action)}>{action.label}</button>)}</div>,document.body)}</>;
}
