'use client';
import Link from 'next/link';
import {useState} from 'react';
import {DashboardLayoutEditor} from './dashboard-layout';
import {defaultDashboardLayout,type DashboardPreference} from '@/shared/dashboard-layout';
import {ArrowUpRight,ScanLine,Plus,MapPin,Wrench,ClipboardCheck,SlidersHorizontal,AlertTriangle} from 'lucide-react';
import type {Dashboard,AssetStatus} from '@/shared/types';
import type {OperationsSummary} from '@/shared/product';
import {deliveryQuantities} from '@/shared/purchase';
import {hasPermission} from '@/shared/permissions';
import {useApp} from './context';
import {AnimatedNumber} from './experience';
import {PageHeader,Loading,ErrorMessage,EmptyState,HistoryList,StatusBadge,statusLabels,useResource,formatDate} from './ui';
export function DashboardScreen(){
 const {user,lookups,operations}=useApp(),preferences=useResource<DashboardPreference>(user.role==='ADMIN'&&hasPermission(user,'dashboard.configure')?'/api/dashboard/layout':null),[editingLayout,setEditingLayout]=useState(false),layout=preferences.data?.layout??defaultDashboardLayout,dashboard=useResource<Dashboard>('/api/dashboard'),data=dashboard.data,ops=operations.data;
 if(dashboard.loading&&!data)return <Loading/>;
 return <><PageHeader eyebrow="ITH // OPERATIONS CENTER" title="Centrum operacyjne" description="Stan infrastruktury. Otwarta praca. Następny ruch." actions={<>{user.role==='ADMIN'&&hasPermission(user,'dashboard.configure')&&<button className="button button-secondary" disabled={!preferences.data} onClick={()=>setEditingLayout(true)}><SlidersHorizontal size={16}/>Mój dashboard</button>}{hasPermission(user,'rfid.scan')&&<Link className="button button-secondary" href="/scan"><ScanLine size={16}/>Skanuj</Link>}{hasPermission(user,'asset.create')&&<Link className="button" href="/assets?create=1"><Plus size={16}/>Dodaj urządzenie</Link>}</>}/><ErrorMessage message={dashboard.error||operations.error||preferences.error} onRetry={()=>{dashboard.reload();operations.reload();preferences.reload();}}/>{data&&<>
 <div className="operations-dateline"><span><span className="status-light success"/>Dane z ewidencji</span><span>{new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Warsaw'}).format(new Date())}</span></div>
 {layout.overview&&<section className="operations-overview">{hasPermission(user,'asset.view')&&<Link className="asset-total" href="/assets"><span>URZĄDZENIA W EWIDENCJI</span><strong><AnimatedNumber value={data.totalAssets}/><ArrowUpRight size={23}/></strong><small>{data.activeAssets} aktywnych urządzeń</small></Link>}<div className="operations-state-strip">{hasPermission(user,'asset.view')&&(Object.keys(statusLabels) as AssetStatus[]).filter(s=>s!=='RETIRED').map(s=><Link key={s} href={'/assets?status='+s}><span className={'status-key status-bg-'+s.toLowerCase()}/><strong>{data.statusCounts[s]||0}</strong><span>{statusLabels[s]}</span><ArrowUpRight size={14}/></Link>)}{hasPermission(user,'inventory.view')&&<Link href="/inventory"><strong>{data.inventoryCount}</strong><span>Produkty magazynowe</span><ArrowUpRight size={14}/></Link>}</div></section>}
 <div className={'operations-workspace '+(!layout.incidents&&!layout.recentAssets&&!layout.activity?'without-primary ':'')+(!layout.scanner&&!layout.shortages&&!layout.locations&&!layout.shortcuts&&!layout.deliveries?'without-aside':'')}><div className="operations-primary">{layout.incidents&&hasPermission(user,'incident.view')&&<section className="operation-section"><div className="section-heading"><div><span className="eyebrow">01 / SERWIS</span><h2>Zgłoszenia do obsługi <span className="count-pill">{ops?.openIncidents??'—'}</span></h2></div><Link className="text-link" href="/incidents?status=active">Wszystkie <ArrowUpRight size={15}/></Link></div>{ops?.recentIncidents.length?<div className="incident-rows">{ops.recentIncidents.map(i=><Link className="incident-row" key={i.id} href={'/incidents/'+i.id}><span className={'incident-priority priority-'+i.priority.toLowerCase()}/><div><strong>{i.title}</strong><small className="mono">{i.number} · {i.assetName??'Zgłoszenie ogólne'}</small></div><span>{i.assignedName??'Nieprzydzielone'}</span><ArrowUpRight size={16}/></Link>)}</div>:ops?<EmptyState title="Brak otwartych zgłoszeń" description="Zgłoszenia zapisane w IT Hardware pojawią się tutaj." action={hasPermission(user,'incident.edit')&&<Link className="text-link" href="/incidents?create=1">Dodaj zgłoszenie →</Link>}/>:<Loading compact/>}</section>}
 {layout.recentAssets&&hasPermission(user,'asset.view')&&<section className="operation-section"><div className="section-heading"><div><span className="eyebrow">02 / EWIDENCJA</span><h2>Ostatnio przyjęte urządzenia</h2></div><Link className="text-link" href="/assets">Baza sprzętu <ArrowUpRight size={15}/></Link></div>{data.recentAssets.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Urządzenie / Asset ID</th><th>Status</th><th>Lokalizacja</th></tr></thead><tbody>{data.recentAssets.map(a=><tr key={a.id}><td><Link className="table-title" href={'/asset/'+a.assetId}>{a.name}</Link><small className="mono">{a.assetId}</small></td><td><StatusBadge status={a.status}/></td><td>{a.locationName??'—'}</td></tr>)}</tbody></table></div>:<EmptyState title="Ewidencja zaczyna się tutaj" description="Dodaj pierwsze urządzenie lub przyjmij dostawę."/>}</section>}
 {layout.activity&&<section className="operation-section"><div className="section-heading"><div><span className="eyebrow">03 / HISTORIA</span><h2>Ostatnia aktywność</h2></div>{hasPermission(user,'audit.view')&&<Link className="text-link" href="/audit">Dziennik <ArrowUpRight size={15}/></Link>}</div><HistoryList items={data.activity}/></section>}</div>
 <aside className="operations-aside">{layout.scanner&&hasPermission(user,'rfid.scan')&&<Link className="scan-entry" href="/scan"><div><span className="eyebrow">IDENTYFIKACJA / QR + RFID</span><ArrowUpRight size={20}/></div><ScanLine size={46}/><h2>Odczytaj.<br/>Otwórz. Działaj.</h2><p>Paszport urządzenia jednym odczytem z aparatu lub czytnika.</p><span className="scan-entry-action">Uruchom skaner <ArrowUpRight size={15}/></span></Link>}
 {layout.shortages&&hasPermission(user,'inventory.view')&&<section className="attention-list"><div className="section-heading"><h2><AlertTriangle size={16}/>Wymagają uwagi</h2><span>{data.lowStockCount}</span></div>{data.lowStock.length?data.lowStock.slice(0,5).map(n=><Link href={'/inventory/'+n.slug} key={n.id}><span><strong>{n.name}</strong><small>{n.locationName??'Bez lokalizacji'}</small></span><span className="mono text-amber">{n.stock} / {n.minimalStock}</span></Link>):<p className="help-note">{data.inventoryCount?'Stany magazynowe powyżej minimum.':'Ustaw minimalne stany produktów, aby śledzić zapotrzebowanie.'}</p>}{data.lowStockCount>0&&<Link className="text-link" href="/inventory?lowStock=true">Lista do uzupełnienia →</Link>}</section>}
 {layout.locations&&hasPermission(user,'location.manage')&&<section className="location-preview"><div className="section-heading"><h2><MapPin size={16}/>Lokalizacje</h2><span>{ops?.locationCount??'—'}</span></div>{lookups?.locations.filter(l=>!l.parentId).slice(0,4).map(l=><Link href={'/locations?selected='+l.id} key={l.id}><MapPin size={14}/><strong>{l.name}</strong>{hasPermission(user,'asset.view')&&<small>{l.assetCount??0} urządzeń</small>}<ArrowUpRight size={13}/></Link>)}<Link className="text-link" href="/locations">Otwórz strukturę →</Link></section>}
 {layout.shortcuts&&<div className="operations-shortcuts">{hasPermission(user,'inventory.run')&&<Link href="/stocktakes"><ClipboardCheck size={18}/><span>Inwentaryzacja<small>{ops?.openInventory??0} otwartych sesji</small></span><ArrowUpRight size={16}/></Link>}{hasPermission(user,'config.view')&&<Link href="/configs"><SlidersHorizontal size={18}/><span>Konfiguracje<small>{ops?.configurationCount??0} w bibliotece</small></span><ArrowUpRight size={16}/></Link>}{hasPermission(user,'incident.view')&&<Link href="/servicenow"><Wrench size={18}/><span>ServiceNow<small>Firmowy portal zgłoszeń</small></span><ArrowUpRight size={16}/></Link>}</div>}
 {layout.deliveries&&hasPermission(user,'invoice.view')&&data.recentDeliveries.length>0&&<section className="delivery-ledger"><div className="section-heading"><h2>Ostatnie dostawy</h2><Link href="/deliveries" className="text-link">Wszystkie</Link></div>{data.recentDeliveries.map(d=><Link key={d.id} href={'/invoices/'+d.invoiceId}><span><strong>{d.invoiceNumber}</strong><small>{d.supplierName} · {formatDate(d.receivedAt)}</small></span><span>{deliveryQuantities(d)}</span></Link>)}</section>}</aside></div></>}{editingLayout&&preferences.data&&<DashboardLayoutEditor preference={preferences.data} onClose={()=>setEditingLayout(false)} onSaved={()=>{setEditingLayout(false);preferences.reload();}}/>}</>;
}
