'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Monitor,ScanLine,Plus,Copy,Settings,Link2,Power,Trash2} from 'lucide-react';
import type {Asset} from '@/shared/types';
import type {InventoryScan} from '@/shared/product';
import {hasPermission} from '@/shared/permissions';
import {defaultDeviceConfig,deviceModeLabels,type DeviceKind,type ManagedDevice,type DeviceConfig,type DevicePairing} from '@/shared/devices';
import {useApp} from './context';
import {TvPairingConfirmation} from './tv-pairing';
import {TvDashboardEditor} from './tv-dashboard-editor';
import {TerminalEditor} from './terminal-editor';
import {LocationPicker} from './pickers';
import {api,ApiFailure,Button,EmptyState,ErrorMessage,Field,Loading,Modal,PageHeader,SuccessMessage,useResource,formatDate} from './ui';
export function DevicesScreen(){
 const {user}=useApp(),resource=useResource<ManagedDevice[]>('/api/devices'),editable=hasPermission(user,'device.manage');
 const [editing,setEditing]=useState<ManagedDevice|null|undefined>(),[pairing,setPairing]=useState<DevicePairing|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState<string|null>(null),[deleting,setDeleting]=useState<ManagedDevice|null>(null),[deleteError,setDeleteError]=useState('');
 useEffect(()=>{const timer=setInterval(resource.reload,10000);return()=>clearInterval(timer);},[resource.reload]);
 async function action(device:ManagedDevice,type:'pairing'|'access'){if(busy)return;setBusy(device.id);setError('');try{const result=await api<DevicePairing>('/api/devices/'+device.id+'/'+type,{method:'POST',body:JSON.stringify({version:device.version,...(type==='access'?{enabled:!device.enabled}:{})})},user.csrfToken);if(type==='pairing')setPairing(result);else setNotice(device.enabled?'Wyłączono urządzenie i odwołano dostęp.':'Włączono urządzenie. Połącz przeglądarkę ponownie.');resource.reload();}catch(e){setError((e as Error).message);resource.reload();}finally{setBusy(null);}}
 async function remove(){if(!deleting||busy)return;setBusy(deleting.id);setDeleteError('');setError('');setNotice('');try{await api('/api/devices/'+deleting.id,{method:'DELETE',body:JSON.stringify({version:deleting.version})},user.csrfToken);setDeleting(null);setNotice(deleting.kind==='TV'?'Usunięto dashboard i odłączono TV.':'Usunięto terminal i odwołano dostęp.');resource.reload();}catch(e){const failure=e as ApiFailure;if([404,409].includes(failure.status)){setDeleting(null);setError(failure.message);}else setDeleteError(failure.message);resource.reload();}finally{setBusy(null);}}
 const localAddress=pairing&&/^localhost$|^127\./.test(new URL(pairing.url).hostname);
 return <><PageHeader eyebrow="ITH // CONNECTED SCREENS" title="Ekrany i terminale" description="Własny link, parowanie kodem i treść ustawiana z jednego panelu." actions={editable?<Button onClick={()=>setEditing(null)}><Plus size={16}/>Dodaj ekran / terminal</Button>:undefined}/><ErrorMessage message={error||resource.error} onRetry={resource.reload}/><SuccessMessage message={notice}/><div className="device-flow"><span>01 · Dodaj urządzenie</span><span>02 · Otwórz link na urządzeniu</span><span>03 · Zatwierdź TV i ustaw widok</span></div>{resource.loading&&!resource.data?<Loading/>:resource.data?.length?<div className="managed-device-list">{resource.data.map(device=><section className="managed-device" key={device.id}><div className="managed-device-heading">{device.kind==='TV'?<Monitor size={25}/>:<ScanLine size={25}/>}<div><h2>{device.name}</h2><p>{device.kind==='TV'?'Telewizor / ekran':'Terminal z przeglądarką'}{device.assetName?' · '+device.assetName:''}</p></div><span className={'device-access '+(!device.enabled?'disabled':device.paired?'paired':'pending')}>{!device.enabled?'Wyłączone':device.paired?'Sparowane':'Oczekuje na parowanie'}</span></div><dl className="managed-device-facts"><div><dt>Wyświetlany widok</dt><dd>{deviceModeLabels[device.config.mode]}</dd></div><div><dt>Ostatni kontakt</dt><dd>{device.lastSeenAt?formatDate(device.lastSeenAt,true):'Jeszcze nie połączono'}</dd></div><div><dt>Motyw / aktualizacja</dt><dd>{device.config.theme==='light'?'Jasny':'Ciemny'} · co {device.config.refreshSeconds} s</dd></div></dl>{device.config.message&&<p className="device-message-preview">{device.config.message}</p>}<div className="row-actions">{editable&&<><Button variant="secondary" disabled={busy!==null} onClick={()=>setEditing(device)}><Settings size={15}/>Ustaw widok</Button><Button variant="secondary" disabled={busy!==null||!device.enabled} onClick={()=>void action(device,'pairing')}><Link2 size={15}/>{device.kind==='TV'?'Połącz TV':'Nowy kod i link'}</Button><Button variant="ghost" disabled={busy!==null} onClick={()=>void action(device,'access')}><Power size={15}/>{device.enabled?'Wyłącz dostęp':'Włącz urządzenie'}</Button><Button variant="danger" disabled={busy!==null} onClick={()=>{setDeleting(device);setDeleteError('');}}><Trash2 size={15}/>{device.kind==='TV'?'Usuń dashboard':'Usuń terminal'}</Button></>}</div></section>)}</div>:<EmptyState title="Połącz pierwszy TV lub terminal" description="Każde urządzenie dostanie własny link. Kod widoczny na TV zatwierdzasz w panelu, a następnie wybierasz dane ekranu." action={editable?<Button onClick={()=>setEditing(null)}>Dodaj urządzenie</Button>:undefined}/>}
 {deleting&&<Modal title={deleting.kind==='TV'?'Usuń dashboard':'Usuń terminal'} onClose={()=>{if(!busy)setDeleting(null);}}><p>Czy usunąć <strong>{deleting.name}</strong>?</p><p>Konfiguracja zostanie trwale usunięta. Link i parowanie przestaną działać, a połączona przeglądarka utraci dostęp przy najbliższym odświeżeniu. Sprzęt w ewidencji i historia operacji zostaną zachowane.</p><ErrorMessage message={deleteError}/><div className="form-actions"><Button variant="secondary" disabled={busy!==null} onClick={()=>setDeleting(null)} data-autofocus>Anuluj</Button><Button variant="danger" disabled={busy!==null} onClick={()=>void remove()}><Trash2 size={15}/>{busy?'Usuwanie…':'Potwierdź usunięcie'}</Button></div></Modal>}
 {editing!==undefined&&<DeviceForm device={editing} onClose={()=>setEditing(undefined)} onSaved={result=>{setEditing(undefined);resource.reload();if('device' in result)setPairing(result);else setNotice('Zapisano widok. Urządzenie pobierze zmianę przy najbliższym odświeżeniu.');}}/>}
 {pairing&&<Modal title={'Połącz: '+pairing.device.name} onClose={()=>setPairing(null)}>{pairing.device.kind==='TV'?<TvPairingConfirmation pairing={pairing} onApproved={()=>{setPairing(null);setNotice('Zatwierdzono TV. Ekran uruchomi się automatycznie.');resource.reload();}}/>:<><p>Otwórz poniższy link w przeglądarce TV lub terminala i wpisz ten kod.</p><div className="device-pair-code" aria-label="Kod parowania">{pairing.code}</div><p className="help-note">Jednorazowy kod ważny do {formatDate(pairing.expiresAt!,true)}. Ponowne parowanie zastąpi dostęp poprzedniej przeglądarki.</p><Field label="Link urządzenia"><input readOnly value={pairing.url} onFocus={e=>e.target.select()}/></Field>{localAddress&&<div className="notice notice-info">Localhost działa tylko na tym komputerze. Na TV i terminalu użyj adresu aplikacji dostępnego w sieci firmowej.</div>}<div className="form-actions"><Button variant="secondary" onClick={()=>setPairing(null)}>Zamknij</Button><Button onClick={async()=>{try{await navigator.clipboard.writeText(pairing.url);setNotice('Skopiowano link urządzenia.');}catch{setError('Skopiuj link bezpośrednio z pola.');}}}><Copy size={15}/>Kopiuj link</Button></div></>}</Modal>}</>;
}
function DeviceForm({device,onClose,onSaved}:{device:ManagedDevice|null;onClose:()=>void;onSaved:(result:ManagedDevice|DevicePairing)=>void}){
 const {user}=useApp(),[name,setName]=useState(device?.name??''),[kind,setKind]=useState<DeviceKind>(device?.kind??'TV'),[config,setConfig]=useState<DeviceConfig>(device?.config??defaultDeviceConfig('TV')),[assetCode,setAssetCode]=useState(''),[unlink,setUnlink]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const scans=useResource<InventoryScan[]>(kind==='SCANNER'?'/api/stocktakes':null);
 function update<K extends keyof DeviceConfig>(key:K,value:DeviceConfig[K]){setConfig(v=>({...v,[key]:value}));}
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{let assetId=unlink?null:device?.assetId??null;if(assetCode.trim())assetId=(await api<Asset>('/api/assets/'+encodeURIComponent(assetCode.trim()))).id;onSaved(await api<ManagedDevice|DevicePairing>('/api/devices'+(device?'/'+device.id:''),{method:device?'PATCH':'POST',body:JSON.stringify({name,kind,assetId,config,...(device?{version:device.version}:{})})},user.csrfToken));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const modes=kind==='TV'?['OVERVIEW','INCIDENTS','MESSAGE'] as const:['LOOKUP','CONTINUOUS','INVENTORY'] as const;
 return <Modal title={device?'Ustaw widok urządzenia':'Dodaj TV lub terminal'} onClose={()=>{if(!busy)onClose();}} wide><form onSubmit={submit}><ErrorMessage message={error||scans.error}/><fieldset disabled={busy} className="plain-fieldset"><div className="form-grid"><Field label="Nazwa urządzenia *"><input required minLength={2} maxLength={120} placeholder="TV magazyn / Terminal 01" value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Typ urządzenia"><select disabled={!!device} value={kind} onChange={e=>{const next=e.target.value as DeviceKind;setKind(next);setConfig(defaultDeviceConfig(next));}}><option value="TV">Telewizor / ekran</option><option value="SCANNER">Terminal z przeglądarką</option></select></Field><Field label="Widok"><select value={config.mode} onChange={e=>setConfig(v=>({...v,mode:e.target.value as DeviceConfig['mode'],stocktakeId:null}))}>{modes.map(mode=><option value={mode} key={mode}>{deviceModeLabels[mode]}</option>)}</select></Field><Field label="Motyw ekranu"><select value={config.theme} onChange={e=>update('theme',e.target.value as 'light'|'dark')}><option value="light">Jasny</option><option value="dark">Ciemny</option></select></Field><Field label="Nagłówek na ekranie"><input maxLength={160} placeholder="Domyślnie nazwa urządzenia" value={config.title} onChange={e=>update('title',e.target.value)}/></Field><Field label="Odświeżanie"><select value={config.refreshSeconds} onChange={e=>update('refreshSeconds',Number(e.target.value))}>{[5,10,15,30,60].map(seconds=><option key={seconds} value={seconds}>Co {seconds} sekund</option>)}</select></Field></div>
 {kind==='TV'&&<><LocationPicker label="Dane z lokalizacji" value={config.locationId??''} onChange={value=>update('locationId',value||null)} emptyLabel="Cała ewidencja"/>{config.mode==='OVERVIEW'&&<div className="device-module-options"><label className="checkbox-inline"><input type="checkbox" checked={config.showStats} onChange={e=>update('showStats',e.target.checked)}/>Statystyki sprzętu</label><label className="checkbox-inline"><input type="checkbox" checked={config.showIncidents} onChange={e=>update('showIncidents',e.target.checked)}/>Otwarte zgłoszenia</label></div>}</>}
 {config.mode==='INVENTORY'&&<Field label="Sesja inwentaryzacji *"><select required value={config.stocktakeId??''} onChange={e=>update('stocktakeId',e.target.value||null)}><option value="">Wybierz otwartą sesję</option>{scans.data?.filter(scan=>scan.status==='OPEN').map(scan=><option key={scan.id} value={scan.id}>{scan.locationName} · {formatDate(scan.startedAt,true)} · {scan.observed}/{scan.expected}</option>)}</select><small>Sesję rozpocznij wcześniej w Inwentaryzacji. Terminal będzie zapisywał odczyty tylko do wybranej sesji.</small></Field>}
 <Field label="Komunikat / powiadomienie na ekranie"><textarea maxLength={2000} rows={3} placeholder="Puste pole ukrywa komunikat." value={config.message} onChange={e=>update('message',e.target.value)}/></Field>{kind==='TV'?<TvDashboardEditor config={config} onChange={setConfig}/>:<TerminalEditor config={config} onChange={setConfig}/>}<Field label="Ważność komunikatu"><select value={config.messageLevel} onChange={e=>update('messageLevel',e.target.value as DeviceConfig['messageLevel'])}><option value="INFO">Informacja</option><option value="WARNING">Ważne</option><option value="CRITICAL">Pilne</option></select></Field>
 <details className="device-asset-binding"><summary>Powiąż z urządzeniem w ewidencji (opcjonalnie)</summary>{device?.assetName&&<p>Obecnie: {device.assetName}. Puste pole zachowa powiązanie.</p>}<Field label="Asset ID TV lub terminala"><input maxLength={13} placeholder="ITHW-00000001" value={assetCode} onChange={e=>{setAssetCode(e.target.value);setUnlink(false);}}/></Field>{device?.assetId&&<label className="checkbox-inline"><input type="checkbox" checked={unlink} onChange={e=>{setUnlink(e.target.checked);if(e.target.checked)setAssetCode('');}}/>Odłącz od ewidencji</label>}</details>
 <div className="form-actions"><Button type="button" variant="secondary" onClick={onClose}>Anuluj</Button><Button disabled={busy||config.mode==='INVENTORY'&&!config.stocktakeId}>{busy?'Zapisywanie…':device?'Zapisz widok':kind==='TV'?'Dodaj TV i otwórz parowanie':'Dodaj i wygeneruj kod'}</Button></div></fieldset></form></Modal>;
}
