'use client';
import {useState,type FormEvent} from 'react';
import {Building2,Layers,Pencil,Plus,Search,Trash2} from 'lucide-react';
import type {Category,CategoryField,Supplier} from '@/shared/types';
import {useApp} from './context';
import {api,Button,EmptyState,ErrorMessage,Field,Modal} from './ui';
import {DeleteEntryModal} from './admin';
import {StandardFieldEditor} from './standard-field-editor';
import type {StandardFields} from '@/shared/asset-fields';
const supplierFields:[keyof Supplier,string,string?][]=[['taxId','NIP / VAT ID'],['regon','REGON'],['street','Ulica, numer budynku / lokalu'],['postalCode','Kod pocztowy'],['city','Miejscowość'],['country','Kraj'],['contactName','Osoba kontaktowa'],['email','E-mail','email'],['phone','Telefon'],['website','Strona WWW','url'],['bankAccount','Numer konta / IBAN'],['notes','Uwagi']];
const fieldTypes:[CategoryField['type'],string][]=[['text','Tekst'],['number','Liczba'],['date','Data'],['boolean','Tak / Nie'],['select','Lista wyboru']];
export function DictionaryEditor({kind,onSaved}:{kind:'categories'|'suppliers';onSaved:(message:string)=>void}){
 const {lookups}=useApp();const [search,setSearch]=useState(''),[editing,setEditing]=useState<Category|Supplier|null|undefined>(undefined),[deleting,setDeleting]=useState<Category|Supplier|null>(null);
 const items=(lookups?.[kind]??[]) as (Category|Supplier)[],category=kind==='categories'; // Admin-only screen: lookups carry full supplier data here.
 const filtered=items.filter(item=>JSON.stringify(item).toLocaleLowerCase('pl').includes(search.toLocaleLowerCase('pl')));
 return <><div className="toolbar"><div className="toolbar-search"><Search size={16}/><input aria-label={category?'Szukaj kategorii':'Szukaj kontrahentów'} placeholder={category?'Nazwa lub pole kategorii…':'Nazwa, NIP, adres lub kontakt…'} value={search} onChange={e=>setSearch(e.target.value)}/></div><Button onClick={()=>setEditing(null)}><Plus size={16}/>{category?'Dodaj kategorię':'Dodaj kontrahenta'}</Button></div><div className="directory-grid">{filtered.map(item=><section className="panel directory-card" key={item.id}><div className="panel-heading"><div><h2>{category?<Layers size={17}/>:<Building2 size={17}/>} {item.name}</h2>{category?<p>{(item as Category).description||'Kategoria sprzętu'}</p>:<p>{[(item as Supplier).street,(item as Supplier).postalCode,(item as Supplier).city,(item as Supplier).country].filter(Boolean).join(', ')||'Uzupełnij adres firmy'}</p>}</div></div><div className="panel-body">{category?<><span className="badge">{(item as Category).fieldDefinitions.length} pól kategorii</span><div className="field-pills">{(item as Category).fieldDefinitions.map(f=><span key={f.key}>{f.label}{f.required?' *':''}</span>)}</div></>:<><p className="help-note">NIP: {(item as Supplier).taxId||'—'} · REGON: {(item as Supplier).regon||'—'}</p><p className="help-note">{[(item as Supplier).contactName,(item as Supplier).email,(item as Supplier).phone].filter(Boolean).join(' · ')||'Brak danych kontaktowych'}</p></>}<div className="row-actions"><Button variant="secondary" onClick={()=>setEditing(item)}><Pencil size={14}/>Edytuj</Button><Button variant="ghost" aria-label={`Usuń ${item.name}`} onClick={()=>setDeleting(item)}><Trash2 size={14}/>Usuń</Button></div></div></section>)}</div>{!filtered.length&&<EmptyState title="Brak wpisów" description="Dodaj nowy wpis lub zmień wyszukiwanie."/>}{editing!==undefined&&<DictionaryModal kind={kind} item={editing} onClose={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);onSaved(category?'Zapisano kategorię i definicje pól.':'Zapisano dane kontrahenta.');}}/>}{deleting&&<DeleteEntryModal name={deleting.name} endpoint={`/api/admin/${kind}/${deleting.id}`} description="Usunąć nieużywany wpis? Wpis powiązany z ewidencją lub fakturą pozostanie chroniony." onClose={()=>setDeleting(null)} onSaved={()=>{setDeleting(null);onSaved('Usunięto wpis.');}}/>}</>;
}
export function DictionaryModal({kind,item,onClose,onSaved,initialName=''}:{kind:'categories'|'suppliers';item:Category|Supplier|null;onClose:()=>void;onSaved:(item:Category|Supplier)=>void;initialName?:string}){
 const {user}=useApp();const category=kind==='categories';
 const [name,setName]=useState(item?.name??initialName),[description,setDescription]=useState((item as Category|null)?.description??'');
 const [standardFields,setStandardFields]=useState<StandardFields>((item as Category|null)?.standardFields??{});
 const [fields,setFields]=useState<CategoryField[]>((item as Category|null)?.fieldDefinitions??[]);
 const [values,setValues]=useState<Record<string,string>>(Object.fromEntries(supplierFields.map(([key])=>[key,String((item as Supplier|null)?.[key]??'')])));
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 function changeField(index:number,patch:Partial<CategoryField>){setFields(previous=>previous.map((f,i)=>i===index?{...f,...patch}:f));}
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const saved=await api<Category|Supplier>(`/api/admin/${kind}${item?'/'+item.id:''}`,{method:item?'PATCH':'POST',body:JSON.stringify({name,...(category?{description,fieldDefinitions:fields,standardFields}:values),...(item?{version:item.version}:{})})},user.csrfToken);onSaved(saved);}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
 return <Modal title={`${item?'Edytuj':'Dodaj'} ${category?'kategorię sprzętu':'kontrahenta'}`} onClose={()=>{if(!busy)onClose();}}><form onSubmit={submit}><ErrorMessage message={error}/><fieldset disabled={busy} className="plain-fieldset"><Field label={category?'Nazwa kategorii *':'Pełna nazwa firmy *'}><input required maxLength={category?120:200} value={name} onChange={e=>setName(e.target.value)}/></Field>{category?<><Field label="Opis"><textarea maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)}/></Field><StandardFieldEditor value={standardFields} onChange={setStandardFields}/><h3>Pola specyficzne dla tej kategorii</h3><p className="help-note">Tutaj dodasz dodatkowe parametry, np. RAM, procesor, rodzaj tonera lub liczbę portów.</p>{fields.map((f,i)=><div className="category-field-editor" key={i}><div className="form-grid"><Field label="Nazwa pola *"><input required maxLength={100} value={f.label} onChange={e=>changeField(i,{label:e.target.value})}/></Field><Field label="Stały klucz *" hint="Klucz łączy pole z zapisanymi danymi."><input required pattern="[a-zA-Z][a-zA-Z0-9_]{0,63}" value={f.key} onChange={e=>changeField(i,{key:e.target.value})}/></Field><Field label="Rodzaj"><select value={f.type} onChange={e=>changeField(i,{type:e.target.value as CategoryField['type']})}>{fieldTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><label className="checkbox-inline"><input type="checkbox" checked={f.required} onChange={e=>changeField(i,{required:e.target.checked})}/>Wymagane</label></div>{f.type==='select'&&<Field label="Opcje (oddziel średnikami) *"><input key={f.key} required defaultValue={f.options?.join('; ')??''} onChange={e=>changeField(i,{options:e.target.value.split(';').map(v=>v.trim()).filter(Boolean)})}/></Field>}<Button type="button" variant="ghost" onClick={()=>setFields(previous=>previous.filter((_,index)=>index!==i))}><Trash2 size={14}/>Usuń definicję pola</Button></div>)}<Button type="button" variant="secondary" disabled={fields.length>=30} onClick={()=>{let n=fields.length+1;while(fields.some(f=>f.key==='field'+n))n++;setFields(previous=>[...previous,{key:'field'+n,label:'',type:'text',required:false}]);}}><Plus size={14}/>Dodaj pole kategorii</Button></>:<div className="form-grid">{supplierFields.map(([key,label,type])=><Field key={key} label={label}>{key==='notes'?<textarea maxLength={4000} value={values[key]} onChange={e=>setValues(previous=>({...previous,[key]:e.target.value}))}/>:<input type={type||'text'} maxLength={key==='website'?500:key==='email'?254:200} value={values[key]} onChange={e=>setValues(previous=>({...previous,[key]:e.target.value}))}/>}</Field>)}</div>}</fieldset><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Anuluj</Button><Button disabled={busy}>{busy?'Zapisywanie…':'Zapisz'}</Button></div></form></Modal>;
}
