'use client';
import {hasPermission} from '@/shared/permissions';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {ArrowLeft,ArrowUpRight,Monitor,Pencil,Plus,Search,UserRound,Users} from 'lucide-react';
import type {Asset,Employee,History} from '@/shared/types';
import {canEdit,useApp} from './context';
import {LocationPicker,SearchSelect} from './pickers';
import {TemporaryPassword} from './temporary-password';
import {EmployeeProfile} from './employee-profile';
import {api,Button,DetailsGrid,EmptyState,ErrorMessage,Field,HistoryList,Loading,Modal,PageHeader,StatusBadge,SuccessMessage,useResource} from './ui';
type Equipment={employee:Employee|null;assets:Asset[];history:History[]};
export function EmployeesScreen({id,mine=false}:{id?:string;mine?:boolean}){return id||mine?<EmployeeProfile id={id} mine={mine}/>:<EmployeeList/>;}
function EmployeeList(){
 const {user,refreshLookups}=useApp(),params=useSearchParams();const resource=useResource<Employee[]>('/api/employees');
 const [search,setSearch]=useState(''),[showInactive,setShowInactive]=useState(false),[editing,setEditing]=useState<Employee|null|undefined>(params.get('create')==='1'?null:undefined),[success,setSuccess]=useState('');
 useEffect(()=>{if(params.get('create')==='1'&&hasPermission(user,'employee.edit'))setEditing(null);},[params,user]);
 const filtered=resource.data?.filter(e=>(showInactive||e.active)&&`${e.name} ${e.employeeNumber??''} ${e.department??''} ${e.email??''}`.toLocaleLowerCase('pl').includes(search.toLocaleLowerCase('pl')));
 return <><PageHeader eyebrow="ZESPÓŁ I SPRZĘT" title="Pracownicy" description="Profile, konta dostępu i aktualnie przypisane urządzenia." actions={hasPermission(user,'employee.edit')&&<Button onClick={()=>setEditing(null)}><Plus size={16}/>Dodaj pracownika</Button>}/><SuccessMessage message={success}/><ErrorMessage message={resource.error} onRetry={resource.reload}/><div className="toolbar"><div className="toolbar-search"><Search size={16}/><input aria-label="Szukaj pracowników" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Imię, dział, numer lub e-mail…"/></div><label className="checkbox-inline"><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/>Pokaż nieaktywnych</label></div><section className="panel"><div className="panel-heading"><h2><Users size={18}/> Baza pracowników <span className="count-pill">{filtered?.length??'—'}</span></h2></div>{resource.loading&&!resource.data?<Loading/>:filtered?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Pracownik</th><th>Dział / stanowisko</th><th>Sprzęt</th><th>Konto</th><th/></tr></thead><tbody>{filtered.map(e=><tr key={e.id}><td><Link className="table-title" href={`/employees/${e.id}`}>{e.name}</Link><small>{e.employeeNumber||e.email||'—'}{!e.active?' · Nieaktywny':''}</small></td><td>{e.department||'—'}<small>{e.position}</small></td><td><span className="badge">{e.assetCount} urządzeń</span></td><td>{e.userId?e.userActive?'Aktywne':'Nieaktywne':'Brak konta'}</td><td><div className="row-actions"><Link className="icon-button" aria-label={`Otwórz profil ${e.name}`} href={`/employees/${e.id}`}><ArrowUpRight size={16}/></Link>{hasPermission(user,'employee.edit')&&<Button variant="ghost" aria-label={`Edytuj pracownika ${e.name}`} onClick={()=>setEditing(e)}><Pencil size={14}/></Button>}</div></td></tr>)}</tbody></table></div>:<EmptyState title="Brak pracowników" description="Dodaj profil lub zmień wyszukiwanie."/>}</section>{editing!==undefined&&<EmployeeForm employee={editing} onClose={()=>setEditing(undefined)} onSaved={()=>{setEditing(undefined);resource.reload();refreshLookups();setSuccess('Zapisano profil pracownika.');}}/>}</>;
}
const employeeFields:[string,string,string?][]=[['employeeNumber','Numer pracownika'],['email','E-mail','email'],['phone','Telefon'],['department','Dział'],['position','Stanowisko'],['notes','Uwagi']];
export function EmployeeForm({employee,onClose,onSaved}:{employee:Employee|null;onClose:()=>void;onSaved:()=>void}){
 const {user,lookups}=useApp();const [name,setName]=useState(employee?.name??''),[values,setValues]=useState<Record<string,string>>(Object.fromEntries(employeeFields.map(([key])=>[key,String(employee?.[key as keyof Employee]??'')]))),[locationId,setLocationId]=useState(employee?.locationId??''),[userId,setUserId]=useState(employee?.userId??''),[active,setActive]=useState(employee?.active??true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{await api(`/api/employees${employee?'/'+employee.id:''}`,{method:employee?'PATCH':'POST',body:JSON.stringify({name,...values,locationId:locationId||null,...(user.role==='ADMIN'?{userId:userId||null}:{}),active,...(employee?{version:employee.version}:{})})},user.csrfToken);onSaved();}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
 return <Modal title={employee?'Edytuj profil pracownika':'Dodaj pracownika'} onClose={()=>{if(!busy)onClose();}}><form onSubmit={submit}><ErrorMessage message={error}/><fieldset disabled={busy} className="plain-fieldset"><Field label="Imię i nazwisko *"><input required minLength={2} maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></Field><div className="form-grid">{employeeFields.map(([key,label,type])=><Field key={key} label={label}>{key==='notes'?<textarea maxLength={4000} value={values[key]} onChange={e=>setValues(previous=>({...previous,[key]:e.target.value}))}/>:<input type={type||'text'} maxLength={key==='email'?254:120} value={values[key]} onChange={e=>setValues(previous=>({...previous,[key]:e.target.value}))}/>}</Field>)}<LocationPicker value={locationId} onChange={setLocationId}/>{user.role==='ADMIN'&&<SearchSelect label="Istniejące konto logowania" value={userId} onSelect={setUserId} placeholder="Wpisz nazwisko lub e-mail konta…" options={(lookups?.users??[]).filter(u=>u.active!==false||u.id===employee?.userId).map(u=>({id:u.id,label:u.name,detail:u.email}))}/>}</div><label className="checkbox-inline"><input type="checkbox" checked={active} disabled={!!employee?.userId&&user.role!=='ADMIN'} onChange={e=>setActive(e.target.checked)}/>Aktywny pracownik</label><p className="help-note">Przed dezaktywacją zwróć lub przekaż przypisany sprzęt. Powiązane konto użytkownika zostanie wyłączone.</p></fieldset><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Anuluj</Button><Button disabled={busy}>{busy?'Zapisywanie…':'Zapisz pracownika'}</Button></div></form></Modal>;
}
export function EmployeeAccount({employee,onClose,onSaved}:{employee:Employee;onClose:()=>void;onSaved:()=>void}){
 const {user}=useApp();const [email,setEmail]=useState(employee.email??''),[password,setPassword]=useState(''),[role,setRole]=useState('IT_USER'),[mustChangePassword,setMustChangePassword]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{await api(`/api/employees/${employee.id}/account`,{method:'POST',body:JSON.stringify({email,password,role,mustChangePassword,version:employee.version})},user.csrfToken);onSaved();}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
 return <Modal title={`Konto: ${employee.name}`} onClose={()=>{if(!busy)onClose();}}><form onSubmit={submit}><fieldset className="plain-fieldset" disabled={busy}><ErrorMessage message={error}/><Field label="E-mail do logowania *"><input type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></Field><TemporaryPassword value={password} onChange={setPassword}/><label className="checkbox-inline"><input type="checkbox" checked={mustChangePassword} onChange={e=>setMustChangePassword(e.target.checked)}/>Wymagaj zmiany hasła przy pierwszym logowaniu</label><p className="help-note">Przekaż użytkownikowi e-mail oraz hasło tymczasowe. Po zalogowaniu ustawi własne hasło.</p><Field label="Uprawnienia"><select value={role} onChange={e=>setRole(e.target.value)}><option value="IT_USER">Pobrania, zwroty i przekazania sprzętu</option><option value="VIEWER">Tylko odczyt ewidencji</option></select></Field><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Anuluj</Button><Button disabled={busy}>{busy?'Tworzenie…':'Utwórz konto'}</Button></div></fieldset></form></Modal>;
}
