'use client';
import {hasPermission} from '@/shared/permissions';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowUpRight,Monitor,Pencil,Plus,UserRound} from 'lucide-react';
import type {Asset,Employee,History} from '@/shared/types';
import {canEdit,canMove,useApp} from './context';
import {EmployeeAccount,EmployeeForm} from './employees';
import {EquipmentDocuments} from './equipment-documents';
import {AssetLinker} from './asset-linker';
import {Button,DetailsGrid,EmptyState,ErrorMessage,HistoryList,Loading,PageHeader,StatusBadge,SuccessMessage,useResource} from './ui';
type Equipment={employee:Employee|null;assets:Asset[];history:History[]};
export function EmployeeProfile({id,mine=false}:{id?:string;mine?:boolean}){
 const {user,refreshLookups}=useApp(),resource=useResource<Equipment>(mine?'/api/my-equipment':`/api/employees/${id}/equipment`);
 const [editing,setEditing]=useState(false),[account,setAccount]=useState(false),[success,setSuccess]=useState(''),employee=resource.data?.employee,assets=resource.data?.assets??[];
 if(resource.loading&&!resource.data)return <Loading/>;
 function saved(message:string){setEditing(false);setAccount(false);setSuccess(message);resource.reload();refreshLookups(['users']);}
 return <><Link className="back-link" href="/employees"><ArrowLeft size={15}/>Baza pracowników</Link><ErrorMessage message={resource.error} onRetry={resource.reload}/><SuccessMessage message={success}/>{employee?<>
 <PageHeader eyebrow={mine?'MOJE KONTO':'PRACOWNIK / WYPOSAŻENIE'} title={employee.name} description={[employee.employeeNumber,employee.department,employee.position].filter(Boolean).join(' · ')} actions={hasPermission(user,'employee.edit')&&<Button variant="secondary" onClick={()=>setEditing(true)}><Pencil size={15}/>Edytuj profil</Button>}/>
 <div className="employee-overview"><div><small>WYDAWANY SPRZĘT</small><strong>{assets.length}</strong><span>urządzeń przypisanych osobiście</span></div><div><small>STATUS PROFILU</small><strong className="employee-status">{employee.active?'Aktywny':'Nieaktywny'}</strong><span>{employee.userId?employee.userActive?'Konto logowania aktywne':'Konto logowania nieaktywne':'Profil bez konta logowania'}</span></div><div><small>LOKALIZACJA</small><strong className="employee-place">{employee.locationName||'Nie wskazano'}</strong><span>{employee.department||'Dział nie został wskazany'}</span></div></div>
 <nav className="passport-tabs" aria-label="Sekcje profilu pracownika"><a href="#employee-equipment">Wyposażenie</a><a href="#employee-documents">Dokumenty / obiegówka</a><a href="#employee-data">Dane i konto</a><a href="#employee-history">Historia</a></nav>
 <section className="panel" id="employee-equipment"><div className="panel-heading"><div><h2><Monitor size={17}/> Osobiste wyposażenie</h2><p>Sprzęt wydany bezpośrednio tej osobie. Wyposażenie stołów ma osobną ewidencję.</p></div><span className="count-pill">{assets.length}</span></div>{employee.active&&hasPermission(user,'asset.assign')&&<div className="panel-body"><AssetLinker mode="employee" targetId={employee.id} targetName={employee.name} onSaved={()=>saved('Zapisano wydanie / przekazanie urządzenia.')}/></div>}{assets.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Urządzenie / model</th><th>Asset ID</th><th>Numer seryjny</th><th>Status</th><th>Lokalizacja</th><th/></tr></thead><tbody>{assets.map(a=><tr key={a.id}><td><Link className="table-title" href={`/asset/${a.assetId}`}>{a.name}</Link><small>{[a.manufacturer,a.model].filter(Boolean).join(' ')}</small></td><td className="mono">{a.assetId}</td><td className="mono">{a.serialNumber||'—'}</td><td><StatusBadge status={a.status}/></td><td>{a.locationName||'—'}</td><td><Link className="button button-secondary" href={`/asset/${a.assetId}`}>{hasPermission(user,'asset.assign')?'Zwrot / przekazanie':'Karta urządzenia'}<ArrowUpRight size={14}/></Link></td></tr>)}</tbody></table></div>:<EmptyState title="Brak osobistego wyposażenia" description="Pracownik magazynowy może korzystać ze sprzętu stołu bez osobistego przypisania. Wydanie laptopa lub innego urządzenia zapiszesz powyżej."/>}</section>
 <div id="employee-documents"><EquipmentDocuments target="employee" id={employee.id}/></div>
 <section className="panel" id="employee-data"><div className="panel-heading"><h2><UserRound size={17}/> Dane pracownika i konto</h2></div><DetailsGrid entries={[["Numer pracownika",employee.employeeNumber],["Dział",employee.department],["Stanowisko",employee.position],["E-mail",employee.email?<a className="text-link" href={`mailto:${employee.email}`}>{employee.email}</a>:null],["Telefon",employee.phone],["Lokalizacja",employee.locationName]]}/>{employee.notes&&<p className="panel-body">{employee.notes}</p>}<div className="panel-body"><div className="row-actions">{user.role==='ADMIN'&&!employee.userId&&employee.active&&<Button variant="secondary" onClick={()=>setAccount(true)}><Plus size={15}/>Utwórz konto pracownika</Button>}{user.role==='ADMIN'&&<Link href="/admin" className="text-link">Zarządzaj kontami i uprawnieniami</Link>}</div><p className="help-note">Dezaktywacja profilu wymaga rozliczenia osobistego sprzętu. Papierowa obiegówka nie wyłącza konta automatycznie.</p></div></section>
 <section className="panel" id="employee-history"><div className="panel-heading"><div><h2>Historia sprzętu pracownika</h2><p>Wydania, przekazania i zwroty; do 500 ostatnich zdarzeń.</p></div></div><HistoryList items={resource.data?.history??[]}/></section>
 {editing&&<EmployeeForm employee={employee} onClose={()=>setEditing(false)} onSaved={()=>saved('Zapisano profil pracownika.')}/>} {account&&<EmployeeAccount employee={employee} onClose={()=>setAccount(false)} onSaved={()=>saved('Utworzono i połączono konto pracownika.')}/>}
 </>:!resource.error&&<EmptyState title={mine?'Połącz konto z profilem pracownika':'Nie znaleziono profilu'} description={mine?'Administrator może połączyć konto w edycji profilu pracownika.':'Wróć do bazy i wybierz pracownika.'}/>}</>;
}
