'use client';
import {createUuid} from '@/shared/uuid';
import {hasPermission} from '@/shared/permissions';
import {useRef,useState} from 'react';
import {Download,FileCheck2,FileText,Mail,Printer} from 'lucide-react';
import type {EquipmentDocument,EquipmentDocumentSummary} from '@/shared/types';
import {documentTitles} from '@/shared/equipment-document';
import {statusLabels} from '@/shared/types';
import {canMove,useApp} from './context';
import {api,Button,EmptyState,ErrorMessage,Field,formatDate,Loading,Modal,useResource} from './ui';

export function EquipmentDocuments({target,id}:{target:'employee'|'workstation';id:string}){
 const {user}=useApp(),resource=useResource<EquipmentDocumentSummary[]>(`/api/${target==='employee'?'employees':'workstations'}/${id}/equipment-documents`);
 const [kind,setKind]=useState<EquipmentDocument['kind']|null>(null),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[document,setDocument]=useState<EquipmentDocument|null>(null);
 const request=useRef<{signature:string;id:string}|null>(null),lock=useRef(false);
 async function create(){if(!kind||lock.current)return;lock.current=true;setBusy(true);setError('');try{
  const signature=JSON.stringify({kind,notes});if(request.current?.signature!==signature)request.current={signature,id:createUuid()};
  const doc=await api<EquipmentDocument>(`/api/${target==='employee'?'employees':'workstations'}/${id}/equipment-documents`,{method:'POST',body:JSON.stringify({kind,notes,requestId:request.current.id})},user.csrfToken);
  setKind(null);setNotes('');request.current=null;resource.reload();setDocument(doc);
 }catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 async function open(id:string){if(busy)return;setBusy(true);setError('');try{setDocument(await api<EquipmentDocument>(`/api/equipment-documents/${id}`));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><div className="panel-heading"><div><h2><FileText size={17}/> Dokumenty wyposażenia</h2><p>Zapisany stan, wydruki i dokumenty do podpisu.</p></div></div><div className="panel-body"><ErrorMessage message={error||resource.error} onRetry={resource.error?resource.reload:undefined}/>{hasPermission(user,'equipment.document')&&<div className="document-actions"><Button disabled={busy} onClick={()=>{setKind(target==='employee'?'equipment':'workstation');setError('');}}><FileText size={16}/>{target==='employee'?'Zapisz kartę wyposażenia':'Zapisz stan stanowiska'}</Button>{target==='employee'&&<Button variant="secondary" disabled={busy} onClick={()=>{setKind('clearance');setError('');}}><FileCheck2 size={16}/>Przygotuj obiegówkę</Button>}</div>}<p className="help-note">{target==='employee'?'Dokument obejmuje wyłącznie urządzenia wydane bezpośrednio pracownikowi.':'Dokument obejmuje wyposażenie tego stołu i jego folderów podrzędnych.'} Zapis pozostaje w historii po zmianie wyposażenia.</p>{resource.loading&&!resource.data?<Loading compact/>:resource.data?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Dokument</th><th>Data / autor</th><th>Sprzęt</th><th/></tr></thead><tbody>{resource.data.map(d=><tr key={d.id}><td><strong>{documentTitles[d.kind]}</strong><small className="mono">{d.reference}</small></td><td>{formatDate(d.createdAt,true)}<small>{d.createdBy}</small></td><td>{d.itemCount} szt.</td><td><Button variant="secondary" disabled={busy} onClick={()=>open(d.id)}>Podgląd / wydruk</Button></td></tr>)}</tbody></table></div>:!resource.error&&<EmptyState title="Brak zapisanych dokumentów" description="Zapisz bieżące wyposażenie lub przygotuj dokument do rozliczenia."/>}</div>
 {kind&&<Modal title={documentTitles[kind]} onClose={()=>{if(!busy)setKind(null);}}><p className="help-note">Zapiszemy bieżącą listę sprzętu wraz z numerami seryjnymi. {kind==='clearance'?'Obiegówka ma pola do ręcznego potwierdzenia zwrotu i podpisy. Zapis dokumentu nie zwraca urządzeń ani nie wyłącza konta.':'Dokument można wydrukować, zapisać jako PDF w oknie drukowania lub przekazać e-mailem.'}</p><ErrorMessage message={error}/><Field label="Uwagi na dokumencie"><textarea maxLength={2000} disabled={busy} value={notes} onChange={e=>setNotes(e.target.value)}/></Field><div className="form-actions"><Button variant="secondary" disabled={busy} onClick={()=>setKind(null)}>Anuluj</Button><Button disabled={busy} onClick={create}>{busy?'Zapisywanie stanu…':'Zapisz i otwórz dokument'}</Button></div></Modal>}
 {document&&<DocumentPreview document={document} onClose={()=>setDocument(null)}/>}</section>;
}
export function DocumentPreview({document:doc,onClose}:{document:EquipmentDocument;onClose:()=>void}){
 const paper=useRef<HTMLDivElement>(null),clearance=doc.kind==='clearance',subject=doc.snapshot.subject;
 function print(){if(!paper.current)return;document.querySelector('.print-only')?.remove();const sheet=document.createElement('div');sheet.className='print-only';sheet.appendChild(paper.current.cloneNode(true));document.body.appendChild(sheet);window.addEventListener('afterprint',()=>sheet.remove(),{once:true});window.print();}
 return <Modal wide title={doc.reference} onClose={onClose}><div className="document-actions"><Button onClick={print}><Printer size={16}/>Drukuj / zapisz PDF</Button><a className="button button-secondary" href={`/api/equipment-documents/${doc.id}/html`} download><Download size={16}/>Pobierz dokument</a><a className="button button-secondary" href={`/api/equipment-documents/${doc.id}/email`} download><Mail size={16}/>Pobierz szkic e-maila</a></div><p className="help-note">Plik .eml zawiera dokument jako załącznik. Otwórz go w programie pocztowym, sprawdź odbiorcę i wyślij. {doc.kind==='workstation'?'Adres odbiorcy wpisz w szkicu.':!subject.email?'Profil nie ma e-maila — wpisz odbiorcę w szkicu.':''}</p><div ref={paper} className="document-paper"><div className="paper-brand">IT HARDWARE<small>R O B A K O W O</small></div><h1>{documentTitles[doc.kind]}</h1><p>{doc.reference} · {formatDate(doc.createdAt,true)}</p><dl><div><dt>{doc.kind==='workstation'?'Stanowisko':'Pracownik'}</dt><dd>{subject.name}</dd></div><div><dt>Numer / lokalizacja</dt><dd>{subject.employeeNumber||subject.locationName||'—'}</dd></div><div><dt>Dział / stanowisko</dt><dd>{[subject.department,subject.position].filter(Boolean).join(' / ')||'—'}</dd></div><div><dt>Dokument przygotował</dt><dd>{doc.createdBy}</dd></div></dl><p>{clearance?'Wypełnić podczas fizycznego rozliczenia. Dokument nie potwierdza zwrotu w systemie.':doc.kind==='workstation'?'Wyposażenie stanowiska. Nie oznacza osobistego wydania pracownikowi.':'Stan sprzętu przypisanego bezpośrednio pracownikowi na dzień zapisu.'}</p><div className="paper-table-wrap"><table><thead><tr><th>Lp.</th><th>Urządzenie / model</th><th>Asset ID</th><th>Numer seryjny</th><th>{clearance?'Zwrócono / brak':'Status'}</th>{clearance&&<><th>Stan / uwagi</th><th>Data / podpis IT</th></>}</tr></thead><tbody>{doc.snapshot.items.length?doc.snapshot.items.map((a,i)=><tr key={a.assetId}><td>{i+1}</td><td><b>{a.name}</b><br/>{a.model}</td><td>{a.assetId}</td><td>{a.serialNumber||'—'}</td><td>{clearance?'':statusLabels[a.status]}</td>{clearance&&<><td/><td/></>}</tr>):<tr><td colSpan={clearance?7:5}>Brak przypisanego sprzętu na dzień zapisu.</td></tr>}</tbody></table></div><p className="paper-notes"><b>Uwagi:</b><br/>{doc.snapshot.notes||'........................................................................................'}</p>{clearance&&<><p>□ Sprzęt sprawdzony fizycznie &nbsp; □ Braki opisane &nbsp; □ Zwroty zapisane w ewidencji</p><p>Data rozliczenia: ........................................</p></>}<div className="paper-signatures"><div>{doc.kind==='workstation'?'Osoba sprawdzająca':'Podpis pracownika'} / data</div><div>Przedstawiciel IT / data</div></div><small>Zapis historyczny {doc.reference}. Późniejsze zmiany ewidencji nie zmieniają dokumentu.</small></div></Modal>;
}
