'use client';
import {useState,type FormEvent} from 'react';
import {Pencil,Plus,Trash2} from 'lucide-react';
import type {InventoryDictionaries,InventoryDictionaryEntry,InventoryDictionaryKind} from '@/shared/inventory-dictionaries';
import {useApp} from './context';
import {api,Button,EmptyState,ErrorMessage,Field,Loading,Modal,useResource} from './ui';

export function InventoryDictionaryEditor({kind,onSaved}:{kind:InventoryDictionaryKind;onSaved:(message:string)=>void}){
 const {user}=useApp(),resource=useResource<InventoryDictionaries>('/api/admin/inventory-dictionaries');
 const [editing,setEditing]=useState<InventoryDictionaryEntry|null|undefined>(),[deleting,setDeleting]=useState<InventoryDictionaryEntry|null>(null),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const category=kind==='category',items=resource.data?.[category?'categories':'units'].filter(e=>(e.name+' '+e.label).toLocaleLowerCase('pl').includes(query.toLocaleLowerCase('pl')))??[];
 const saved=()=>{setEditing(undefined);resource.reload();onSaved('Zapisano '+(category?'kategorię magazynową.':'jednostkę.'));};
 async function remove(){if(!deleting||busy)return;setBusy(true);setError('');try{await api('/api/admin/inventory-dictionaries/'+deleting.id,{method:'DELETE',body:JSON.stringify({version:deleting.version})},user.csrfToken);setDeleting(null);resource.reload();onSaved('Usunięto nieużywany wpis.');}catch(failure){setError((failure as Error).message);}finally{setBusy(false);}}
 return <><p className="help-note">{category?'Kategorie wybierane na kartach produktów magazynowych.':'Jednostki i precyzja ilości (0–3 miejsca po przecinku).'} Wyłączony wpis pozostaje przy istniejących produktach. Używany wpis możesz wyłączyć zamiast usuwać.</p><div className="toolbar"><input aria-label={category?'Szukaj kategorii magazynowej':'Szukaj jednostki'} placeholder="Szukaj na liście…" value={query} onChange={e=>setQuery(e.target.value)}/><Button onClick={()=>setEditing(null)}><Plus size={15}/>{category?'Dodaj kategorię magazynową':'Dodaj jednostkę'}</Button></div><ErrorMessage message={resource.error} onRetry={resource.reload}/>{resource.loading&&!resource.data?<Loading/>:items.length?<section className="panel table-wrap"><table className="data-table"><thead><tr><th>{category?'Kategoria':'Symbol'}</th>{!category&&<><th>Nazwa jednostki</th><th>Precyzja</th></>}<th>Status</th><th>Produkty</th><th>Akcje</th></tr></thead><tbody>{items.map(e=><tr key={e.id}><td><strong>{e.name}</strong></td>{!category&&<><td>{e.label}</td><td>{e.quantityPrecision===0?'Całe sztuki':e.quantityPrecision+' miejsca po przecinku'}</td></>}<td>{e.active?'Aktywna':'Wyłączona'}</td><td>{e.used}</td><td><div className="row-actions"><Button variant="secondary" aria-label={'Edytuj '+e.name} onClick={()=>setEditing(e)}><Pencil size={14}/>Edytuj</Button><Button variant="ghost" aria-label={'Usuń '+e.name} disabled={e.used>0} onClick={()=>{setError('');setDeleting(e);}}><Trash2 size={14}/>Usuń</Button></div></td></tr>)}</tbody></table></section>:!resource.error&&<EmptyState title="Brak wpisów" description="Dodaj wpis lub zmień wyszukiwanie."/>}
 {editing!==undefined&&<EntryModal key={editing?.id??'new'} kind={kind} item={editing} onClose={()=>setEditing(undefined)} onSaved={saved}/>}
 {deleting&&<Modal title="Usuń nieużywany wpis" onClose={()=>{if(!busy)setDeleting(null);}}><p>Usunąć „{deleting.name}” z listy?</p><ErrorMessage message={error}/><div className="form-actions"><Button variant="secondary" disabled={busy} onClick={()=>setDeleting(null)} data-autofocus>Anuluj</Button><Button disabled={busy} onClick={remove}>{busy?'Usuwanie…':'Usuń wpis'}</Button></div></Modal>}
 </>;
}
function EntryModal({kind,item,onClose,onSaved}:{kind:InventoryDictionaryKind;item:InventoryDictionaryEntry|null;onClose:()=>void;onSaved:()=>void}){
 const {user}=useApp(),[name,setName]=useState(item?.name??''),[label,setLabel]=useState(item?.label??''),[active,setActive]=useState(item?.active??true),[precision,setPrecision]=useState(item?.quantityPrecision??0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const category=kind==='category';
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{await api('/api/admin/inventory-dictionaries'+(item?'/'+item.id:''),{method:item?'PATCH':'POST',body:JSON.stringify({kind,name,label:category?name:label,active,...(!category?{quantityPrecision:precision}:{}),...(item?{version:item.version}:{})})},user.csrfToken);onSaved();}catch(failure){setError((failure as Error).message);}finally{setBusy(false);}}
 return <Modal title={(item?'Edytuj ':'Dodaj ')+(category?'kategorię magazynową':'jednostkę')} onClose={()=>{if(!busy)onClose();}}><form onSubmit={submit}><ErrorMessage message={error}/><fieldset disabled={busy} className="plain-fieldset"><Field label={category?'Nazwa kategorii *':'Symbol jednostki *'} hint={!category&&item?.used?'Symbol używanej jednostki pozostaje stały. Edytuj pełną nazwę lub aktywność.':undefined}><input autoFocus required maxLength={category?120:30} readOnly={!category&&!!item?.used} value={name} placeholder={category?'np. Akcesoria montażowe':'np. kpl.'} onChange={e=>setName(e.target.value)}/></Field>{!category&&<Field label="Pełna nazwa jednostki *"><input required maxLength={160} value={label} placeholder="np. komplet" onChange={e=>setLabel(e.target.value)}/></Field>}{!category&&<Field label="Precyzja ilości" hint={item?.used?'Precyzję używanej jednostki można zwiększyć. Zmniejszenie wymaga nowej jednostki.':'Urządzenia zawsze liczymy w całych sztukach.'}><select value={precision} onChange={e=>setPrecision(Number(e.target.value))}>{[0,1,2,3].map(value=><option key={value} value={value} disabled={!!item?.used&&value<(item.quantityPrecision??0)}>{value===0?'Całe sztuki (1, 2, 3)':value+' miejsca po przecinku'}</option>)}</select></Field>}<label className="checkbox-inline" style={{marginTop:16}}><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Aktywna — dostępna dla nowych produktów</label></fieldset><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Anuluj</Button><Button disabled={busy}>{busy?'Zapisywanie…':'Zapisz'}</Button></div></form></Modal>;
}
