'use client';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useEffect,useState,type FormEvent} from 'react';
import {ArrowDown,ArrowUp,ArrowUpRight,ChevronLeft,ChevronRight,Columns3,LayoutGrid,List,Minus,Plus,RefreshCw,Search,Truck,X} from 'lucide-react';
import type {InventoryItem,PageResult} from '@/shared/types';
import {hasPermission} from '@/shared/permissions';
import {inventoryShortage,inventoryState,inventorySortLabels,stockStateLabels,type InventoryCategory,type InventoryPage,type InventorySort,type InventoryStockState} from '@/shared/inventory';
import {useApp} from './context';
import {LocationPicker,SearchSelect,type Choice} from './pickers';
import {ContextMenu,type MenuAction} from './context-menu';
import {InventoryForm,StockCorrectionModal} from './inventory';
import {InventoryMovementModal} from './inventory-movement';
import {api,Button,EmptyState,ErrorMessage,Field,Loading,Modal,PageHeader,QRLabel,SuccessMessage,formatDate,useResource} from './ui';

const defaultColumns={sku:false,productCode:false,category:true,minimum:true,shortage:true,location:true,updatedAt:false};
const columnLabels={sku:'SKU',productCode:'Kod producenta',category:'Kategoria',minimum:'Minimum',shortage:'Niedobór',location:'Lokalizacja',updatedAt:'Aktualizacja'};
type Columns=typeof defaultColumns;
const sorts:[string,string][]=[['name:asc','Nazwa A–Z'],['name:desc','Nazwa Z–A'],['shortage:desc','Największe niedobory'],['stock:asc','Najmniejszy stan'],['stock:desc','Największy stan'],['updatedAt:desc','Ostatnio zmienione'],['category:asc','Kategoria A–Z'],['location:asc','Lokalizacja A–Z'],['sku:asc','SKU A–Z'],['minimum:desc','Największe minimum']];
const number=(value:number)=>value.toLocaleString('pl-PL');
function initialNumber(value:string|null,fallback:number,max:number){const parsed=Number(value);return value&&Number.isInteger(parsed)&&parsed>=1&&parsed<=max?parsed:fallback;}
async function searchCategories(text:string,signal:AbortSignal):Promise<Choice[]>{const result=await api<PageResult<InventoryCategory>>('/api/inventory/facets/categories?q='+encodeURIComponent(text),{signal});return categoryChoices(result.items);}
function categoryChoices(items:InventoryCategory[]):Choice[]{return items.map(item=>({id:encodeURIComponent(item.name),label:item.name,detail:number(item.count)+' pozycji w katalogu'}));}
export function InventoryListScreen(){
 const searchParams=useSearchParams(),{user,lookupError,operations}=useApp();
 const [query,setQuery]=useState(searchParams.get('q')||''),[debounced,setDebounced]=useState(query),[category,setCategory]=useState(searchParams.get('category')||''),[locationId,setLocationId]=useState(searchParams.get('locationId')||''),[noLocation,setNoLocation]=useState(searchParams.get('noLocation')==='true'),[includeChildren,setIncludeChildren]=useState(searchParams.get('includeChildren')!=='false');
 const initialState=searchParams.get('stockState')||(searchParams.get('lowStock')==='true'?'low':'all');
 const [stockState,setStockState]=useState<InventoryStockState>(initialState in stockStateLabels?initialState as InventoryStockState:'all');
 const [sort,setSort]=useState<InventorySort>((searchParams.get('sort')||'name') in inventorySortLabels?(searchParams.get('sort')||'name') as InventorySort:'name'),[direction,setDirection]=useState<'asc'|'desc'>(searchParams.get('direction')==='desc'||!searchParams.has('direction')&&['shortage','updatedAt'].includes(searchParams.get('sort')||'')?'desc':'asc');
 const [page,setPage]=useState(initialNumber(searchParams.get('page'),1,1000000)),[pageSize,setPageSize]=useState(initialNumber(searchParams.get('pageSize'),50,100));
 const [view,setView]=useState<'table'|'cards'>(searchParams.get('view')==='cards'?'cards':'table'),[compact,setCompact]=useState(searchParams.get('compact')!=='false'),[columns,setColumns]=useState<Columns>(defaultColumns);
 const [creating,setCreating]=useState(false),[editing,setEditing]=useState<InventoryItem|null>(null),[correcting,setCorrecting]=useState<InventoryItem|null>(null),[movement,setMovement]=useState<{item:InventoryItem;direction:1|-1}|null>(null),[label,setLabel]=useState<InventoryItem|null>(null),[success,setSuccess]=useState('');
 const preferenceKey='ith-warehouse-view:'+user.id;
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(preferenceKey)||'null');if(!saved)return;if(!searchParams.has('view')&&['table','cards'].includes(saved.view))setView(saved.view);if(!searchParams.has('compact')&&typeof saved.compact==='boolean')setCompact(saved.compact);if(!searchParams.has('pageSize')&&[25,50,100].includes(saved.pageSize))setPageSize(saved.pageSize);if(saved.columns)setColumns(Object.fromEntries(Object.entries(defaultColumns).map(([key,value])=>[key,typeof saved.columns[key]==='boolean'?saved.columns[key]:value])) as Columns);}catch{}},[preferenceKey]);
 function preference(change:Record<string,unknown>){try{localStorage.setItem(preferenceKey,JSON.stringify({view,compact,pageSize,columns,...change}));}catch{}}
 useEffect(()=>{if(query===debounced)return;const timer=setTimeout(()=>{setDebounced(query);setPage(1);},250);return()=>clearTimeout(timer);},[query,debounced]);
 const params=new URLSearchParams({page:String(page),pageSize:String(pageSize),sort,direction,stockState,overview:'true'});
 if(debounced.trim())params.set('q',debounced.trim());if(category)params.set('category',category);if(locationId){params.set('locationId',locationId);params.set('includeChildren',String(includeChildren));}if(noLocation)params.set('noLocation','true');
 const resource=useResource<InventoryPage>('/api/inventory?'+params.toString()),categories=useResource<PageResult<InventoryCategory>>('/api/inventory/facets/categories');
 const {data,error,loading}=resource,updating=loading||query!==debounced;
 const listParams=new URLSearchParams(params);listParams.delete('overview');listParams.set('view',view);listParams.set('compact',String(compact));
 const listHref='/inventory?'+listParams.toString();
 useEffect(()=>{if(window.location.pathname==='/inventory'&&window.location.pathname+window.location.search!==listHref)window.history.replaceState(null,'',listHref);},[listHref]);
 useEffect(()=>{if(!loading&&data?.page===page&&page>Math.max(1,Math.ceil(data.total/pageSize)))setPage(Math.max(1,Math.ceil(data.total/pageSize)));},[data,loading,page,pageSize]);
 function state(value:InventoryStockState){setStockState(value);setPage(1);}
 function clear(){setQuery('');setDebounced('');setCategory('');setLocationId('');setNoLocation(false);setIncludeChildren(true);setStockState('all');setPage(1);}
 function order(key:InventorySort){setDirection(sort===key&&direction==='asc'?'desc':'asc');setSort(key);setPage(1);}
 function changed(message:string){setSuccess(message);resource.reload();categories.reload();operations.reload();}
 const filtered=!!(query||category||locationId||noLocation||stockState!=='all');
 const stock= data?.summary;
 const headline=([{key:'all',label:'Produkty w magazynie',value:stock?.products},{key:'low',label:'Do uzupełnienia',value:stock?.low},{key:'out',label:'Brak na stanie',value:stock?.out},{key:'ok',label:'Stan prawidłowy',value:stock?.ok}] as const);
 const productHref=(item:InventoryItem)=>'/inventory/'+item.slug+'?returnTo='+encodeURIComponent(listHref);
 const actions=(item:InventoryItem):MenuAction[]=>[
  {label:'Otwórz produkt',href:productHref(item)},
  ...(hasPermission(user,'inventory.move')?[{label:'Pobierz z magazynu',onClick:()=>setMovement({item,direction:-1}),disabled:!item.stock||updating},{label:'Przyjmij zwrot',onClick:()=>setMovement({item,direction:1}),disabled:updating}]:[]),
  ...(hasPermission(user,'inventory.edit')?[{label:'Edytuj produkt',onClick:()=>setEditing(item),disabled:updating},{label:'Korekta po przeliczeniu',onClick:()=>setCorrecting(item),disabled:updating}]:[]),
  {label:'Historia ruchów',href:productHref(item)+'#inventory-history'},
  ...(hasPermission(user,'label.print')?[{label:'Etykieta QR',onClick:()=>setLabel(item)}]:[])
 ];
 function rowActions(item:InventoryItem){return <div className="warehouse-row-actions">{hasPermission(user,'inventory.move')&&<Button variant="secondary" className="warehouse-take" disabled={!item.stock||updating} onClick={()=>setMovement({item,direction:-1})} aria-label={'Pobierz: '+item.name}><Minus size={13}/>Pobierz</Button>}<ContextMenu label={'Akcje produktu '+item.name} items={actions(item)}/></div>;}
 function heading(key:InventorySort,labelText:string){return <th scope="col" aria-sort={sort===key?direction==='asc'?'ascending':'descending':'none'}><button type="button" className="sort-heading" onClick={()=>order(key)}>{labelText}{sort===key&&(direction==='asc'?<ArrowUp size={12}/>:<ArrowDown size={12}/>)}</button></th>;}
 return <>
  <div className="warehouse-page-header"><PageHeader eyebrow="ITH // MAGAZYN" title="Magazyn" description="Znajdź produkt, sprawdź stan i wykonaj pobranie lub zwrot." actions={<>{hasPermission(user,'invoice.edit')&&<Link href="/deliveries?receive=1" className="button button-secondary"><Truck size={16}/>Przyjmij dostawę</Link>}{hasPermission(user,'inventory.edit')&&<Button onClick={()=>setCreating(true)}><Plus size={16}/>Dodaj produkt</Button>}{hasPermission(user,'import.run')&&<Link href="/import" className="button button-ghost">Import Excel / CSV</Link>}</>}/></div>
  <SuccessMessage message={success}/>
  <div className="warehouse-summary" aria-label="Stan magazynu w wybranym zakresie">{headline.map(metric=><button type="button" key={metric.key} className={'warehouse-summary-item state-'+metric.key} aria-pressed={stockState===metric.key} onClick={()=>state(metric.key)}><span>{metric.label}</span><strong>{metric.value===undefined?'—':number(metric.value)}</strong><small>{metric.key==='low'?'Stan na minimum lub poniżej':metric.key==='out'?'Produkty bez dostępnych sztuk':metric.key==='ok'?'Stan powyżej minimum':'Pozycje, nie suma sztuk'}</small></button>)}</div>
  <section className="warehouse-workbench" aria-label="Wyszukiwanie i lista magazynu">
   <div className="warehouse-search-row"><div className="warehouse-search"><Search size={18}/><input aria-label="Szukaj produktów" maxLength={200} placeholder="Nazwa, SKU, kod producenta, kategoria lub lokalizacja…" value={query} onChange={event=>setQuery(event.target.value)}/>{query&&<button type="button" className="icon-button" aria-label="Wyczyść wyszukiwanie" onClick={()=>setQuery('')}><X size={16}/></button>}</div><Button variant="ghost" onClick={()=>{resource.reload();categories.reload();}} aria-label="Odśwież stany" disabled={loading}><RefreshCw size={16}/></Button></div>
   <div className="warehouse-filters"><SearchSelect label="Kategoria" value={category?encodeURIComponent(category):''} selectedLabel={category} options={categoryChoices(categories.data?.items??[])} search={searchCategories} onSelect={value=>{setCategory(value?decodeURIComponent(value):'');setPage(1);}} placeholder="Wszystkie kategorie" emptyLabel="Wszystkie kategorie"/>{hasPermission(user,'location.view')&&<LocationPicker label="Lokalizacja magazynowa" value={locationId} onChange={value=>{setLocationId(value);setNoLocation(false);setPage(1);}} emptyLabel="Wszystkie lokalizacje"/>}<Field label="Stan produktu"><select value={stockState} onChange={event=>state(event.target.value as InventoryStockState)}>{Object.entries(stockStateLabels).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></Field><Field label="Sortowanie"><select value={sort+':'+direction} onChange={event=>{const [key,dir]=event.target.value.split(':');setSort(key as InventorySort);setDirection(dir as 'asc'|'desc');setPage(1);}}>{!sorts.some(([value])=>value===sort+':'+direction)&&<option value={sort+':'+direction}>{inventorySortLabels[sort]} {direction==='asc'?'rosnąco':'malejąco'}</option>}{sorts.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></Field></div>
   <div className="warehouse-filter-options">{locationId&&<label className="checkbox-inline"><input type="checkbox" checked={includeChildren} onChange={event=>{setIncludeChildren(event.target.checked);setPage(1);}}/>Uwzględnij podfoldery</label>}{hasPermission(user,'location.view')&&<label className="checkbox-inline"><input type="checkbox" checked={noLocation} onChange={event=>{setNoLocation(event.target.checked);if(event.target.checked)setLocationId('');setPage(1);}}/>Bez lokalizacji</label>}{filtered&&<Button variant="ghost" className="warehouse-clear" onClick={clear}><X size={13}/>Wyczyść filtry</Button>}<span>Podsumowanie obejmuje wyszukiwanie, kategorię i lokalizację.</span></div>
   <ErrorMessage message={error||categories.error||lookupError} onRetry={()=>{resource.reload();categories.reload();}}/>
   <div className="warehouse-list-toolbar"><div aria-live="polite">{updating?<span className="muted">Aktualizowanie wyników…</span>:<><strong>{number(data?.total??0)}</strong> pasujących produktów</>}</div><div className="warehouse-view-toggle" role="group" aria-label="Widok magazynu"><Button variant="ghost" aria-label="Widok tabeli" aria-pressed={view==='table'} onClick={()=>{setView('table');preference({view:'table'});}}><List size={16}/><span>Tabela</span></Button><Button variant="ghost" aria-label="Widok kafelków" aria-pressed={view==='cards'} onClick={()=>{setView('cards');preference({view:'cards'});}}><LayoutGrid size={15}/><span>Kafelki</span></Button></div>{view==='table'&&<><label className="checkbox-inline warehouse-compact"><input type="checkbox" checked={compact} onChange={event=>{setCompact(event.target.checked);preference({compact:event.target.checked});}}/>Zwarta tabela</label><details className="column-settings warehouse-columns"><summary><Columns3 size={14}/>Kolumny</summary><div>{Object.entries(columnLabels).map(([key,value])=><label key={key}><input type="checkbox" checked={columns[key as keyof Columns]} onChange={()=>{const next={...columns,[key]:!columns[key as keyof Columns]};setColumns(next);preference({columns:next});}}/>{value}</label>)}</div></details></>}<label className="warehouse-page-size">Na stronie<select aria-label="Produkty na stronie" value={pageSize} onChange={event=>{const size=Number(event.target.value);setPageSize(size);setPage(1);preference({pageSize:size});}}>{![25,50,100].includes(pageSize)&&<option value={pageSize}>{pageSize}</option>}{[25,50,100].map(size=><option key={size} value={size}>{size}</option>)}</select></label></div>
   {loading&&!data?<Loading/>:data?.items.length?<>
    {view==='table'?<div className="warehouse-table-scroll" tabIndex={0} role="region" aria-label="Tabela produktów magazynowych" aria-busy={updating}><table className={'data-table warehouse-table '+(compact?'is-compact':'')}><thead><tr>{heading('name','Produkt')}{columns.sku&&heading('sku','SKU')}{columns.productCode&&<th scope="col">Kod producenta</th>}{columns.category&&heading('category','Kategoria')}{heading('stock','Stan')}{columns.minimum&&heading('minimum','Minimum')}{columns.shortage&&heading('shortage','Niedobór')}{columns.location&&heading('location','Lokalizacja')}{columns.updatedAt&&heading('updatedAt','Aktualizacja')}<th scope="col">Akcje</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td className="warehouse-item-cell" data-label="Produkt"><Link href={productHref(item)}><strong>{item.name}</strong><small className="mono">{item.sku||item.productCode||item.slug}</small></Link></td>{columns.sku&&<td className="mono" data-label="SKU">{item.sku||'—'}</td>}{columns.productCode&&<td className="mono" data-label="Kod producenta">{item.productCode||'—'}</td>}{columns.category&&<td data-label="Kategoria">{item.category}</td>}<td data-label="Stan"><InventoryStock item={item}/></td>{columns.minimum&&<td className="warehouse-numeric" data-label="Minimum">{number(item.minimalStock)} <small>{item.unit}</small></td>}{columns.shortage&&<td className="warehouse-numeric" data-label="Niedobór"><Shortage item={item}/></td>}{columns.location&&<td className="warehouse-location" data-label="Lokalizacja" title={item.locationName||''}>{item.locationName||<span className="muted">Bez lokalizacji</span>}</td>}{columns.updatedAt&&<td data-label="Aktualizacja"><time dateTime={item.updatedAt}>{formatDate(item.updatedAt,true)}</time></td>}<td className="warehouse-actions-cell" data-label="Akcje">{rowActions(item)}</td></tr>)}</tbody></table></div>:<div className="warehouse-cards" aria-busy={updating}>{data.items.map(item=><article key={item.id} className="warehouse-card"><div className="warehouse-card-top"><span>{item.category}</span><ContextMenu label={'Akcje produktu '+item.name} items={actions(item)}/></div><Link href={productHref(item)}><h2>{item.name}<ArrowUpRight size={15}/></h2><p className="mono">{item.sku||item.productCode||item.slug}</p></Link><p className="warehouse-card-location">{item.locationName||'Bez lokalizacji'}</p><div className="warehouse-card-bottom"><InventoryStock item={item}/><div><span>Minimum: {number(item.minimalStock)} {item.unit}</span><Shortage item={item}/></div></div>{hasPermission(user,'inventory.move')&&<div className="warehouse-card-actions"><Button variant="secondary" disabled={!item.stock||updating} onClick={()=>setMovement({item,direction:-1})} aria-label={'Pobierz: '+item.name}><Minus size={14}/>Pobierz</Button><Button variant="ghost" disabled={updating} onClick={()=>setMovement({item,direction:1})} aria-label={'Zwróć: '+item.name}><Plus size={14}/>Zwrot</Button></div>}</article>)}</div>}
    <WarehousePagination total={data.total} page={page} pageSize={pageSize} disabled={updating} onChange={setPage}/>
   </>:!error&&<EmptyState title={filtered?'Brak pasujących produktów':'Dodaj pierwszy produkt magazynowy'} description={filtered?'Zmień zakres wyszukiwania lub wyczyść filtry.':'Załóż kartę produktu, określ minimum i przyjmij pierwszą dostawę.'} action={filtered?<Button variant="secondary" onClick={clear}>Wyczyść filtry</Button>:hasPermission(user,'inventory.edit')?<Button onClick={()=>setCreating(true)}>Dodaj produkt</Button>:undefined}/>}
  </section>
  {hasPermission(user,'asset.view')&&<p className="warehouse-serial-link">Urządzenia z numerami seryjnymi znajdziesz w <Link href="/assets">Bazie sprzętu <ArrowUpRight size={12}/></Link>.</p>}
  {creating&&<InventoryForm onClose={()=>setCreating(false)} onSaved={item=>{setCreating(false);changed('Dodano '+item.name+'. Przyjmij dostawę, aby wprowadzić stan.');}}/>}
  {editing&&<InventoryForm item={editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);changed('Zapisano dane produktu.');}}/>}
  {correcting&&<StockCorrectionModal item={correcting} onClose={()=>setCorrecting(null)} onSaved={()=>{setCorrecting(null);changed('Korekta zapisana w historii.');}}/>}
  {movement&&<InventoryMovementModal item={movement.item} direction={movement.direction} onClose={()=>setMovement(null)} onSaved={(_item,message)=>{setMovement(null);changed(message);}}/>}
  {label&&<Modal title={'Etykieta: '+label.name} onClose={()=>setLabel(null)}><QRLabel type="inventory" id={label.slug} name={label.name}/></Modal>}
 </>;
}
function InventoryStock({item}:{item:InventoryItem}){const state=inventoryState(item);return <div className={'warehouse-stock stock-'+state}><div><strong>{number(item.stock)}</strong><span>{item.unit}</span></div><small><i aria-hidden="true"/>{state==='out'?'Brak':state==='low'?'Na minimum lub poniżej':'Dostępny'}</small></div>;}
function Shortage({item}:{item:InventoryItem}){const shortage=inventoryShortage(item);return shortage?<span className="warehouse-shortage">{number(shortage)} {item.unit}</span>:item.stock===item.minimalStock&&item.stock>0?<span className="warehouse-shortage">Na minimum</span>:<span className="muted">—</span>;}
function WarehousePagination({total,page,pageSize,disabled,onChange}:{total:number;page:number;pageSize:number;disabled:boolean;onChange:(page:number)=>void}){
 const pages=Math.max(1,Math.ceil(total/pageSize)),[target,setTarget]=useState(String(page));useEffect(()=>setTarget(String(page)),[page]);
 function jump(event:FormEvent){event.preventDefault();const value=Number(target);if(Number.isInteger(value)&&value>=1&&value<=pages)onChange(value);}
 return <nav className="warehouse-pagination" aria-label="Strony magazynu"><span>{number((page-1)*pageSize+1)}–{number(Math.min(page*pageSize,total))} z {number(total)}</span><div><Button variant="ghost" disabled={disabled||page===1} onClick={()=>onChange(1)}>Pierwsza</Button><Button variant="secondary" aria-label="Poprzednia strona magazynu" disabled={disabled||page<=1} onClick={()=>onChange(page-1)}><ChevronLeft size={16}/></Button><form onSubmit={jump}><label>Strona <input aria-label="Numer strony magazynu" type="number" min={1} max={pages} step={1} value={target} onChange={event=>setTarget(event.target.value)} disabled={disabled}/> z {number(pages)}</label><Button variant="ghost" disabled={disabled} type="submit">Idź</Button></form><Button variant="secondary" aria-label="Następna strona magazynu" disabled={disabled||page>=pages} onClick={()=>onChange(page+1)}><ChevronRight size={16}/></Button><Button variant="ghost" disabled={disabled||page===pages} onClick={()=>onChange(pages)}>Ostatnia</Button></div></nav>;
}
