'use client';
import {createUuid} from '@/shared/uuid';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {ArrowLeft,Copy,Download,FileText,Plus,Search,Upload} from 'lucide-react';
import type {EquipmentDocument} from '@/shared/types';
import {DocumentPreview} from './equipment-documents';
import type {Configuration,ConfigurationDetail,LibraryDocument} from '@/shared/product';
import {hasPermission} from '@/shared/permissions';
import {useApp} from './context';
import {api,Button,EmptyState,ErrorMessage,Field,formatDate,Loading,Modal,PageHeader,SuccessMessage,useResource} from './ui';

export function ConfigurationsScreen({id}:{id?:string}){
 const {user}=useApp(),router=useRouter(),params=useSearchParams();const [q,setQ]=useState(''),[edit,setEdit]=useState(params.get('create')==='1'),[versionId,setVersionId]=useState(params.get('version')??''),[notice,setNotice]=useState('');
 const list=useResource<Configuration[]>(id?null:`/api/configs?q=${encodeURIComponent(q)}`),detail=useResource<ConfigurationDetail>(id?`/api/configs/${id}${versionId?'?versionId='+versionId:''}`:null),canEdit=hasPermission(user,'config.edit');
 useEffect(()=>{if(params.get('create')==='1'&&hasPermission(user,'config.edit'))setEdit(true);},[params,user]);
 const config=detail.data;function saved(value:ConfigurationDetail){setEdit(false);setVersionId('');detail.reload();list.reload();router.push(`/configs/${value.id}`);}
 return <>{id&&<Link className="back-link" href="/configs"><ArrowLeft size={15}/>Biblioteka konfiguracji</Link>}<PageHeader eyebrow="ITH // CONFIG" title={config?.name??'Biblioteka konfiguracji'} description={id?'Treść, wersje i informacje o urządzeniach.':'Konfiguracje zespołu IT. Każdy zapis tworzy zachowaną wersję.'} actions={canEdit&&<Button onClick={()=>setEdit(true)}><Plus size={16}/>{id?'Zapisz nową wersję':'Dodaj konfigurację'}</Button>}/><ErrorMessage message={list.error||detail.error} onRetry={()=>{list.reload();detail.reload();}}/><SuccessMessage message={notice}/>{id?detail.loading&&!config?<Loading/>:config&&<>
 <div className="config-metadata"><span>{[config.manufacturer,config.model,config.categoryName].filter(Boolean).join(' / ')||'Ogólna konfiguracja'}</span><span>v{config.latestVersion} · {formatDate(config.updatedAt,true)} · {config.author}</span></div>{config.description&&<p className="config-description">{config.description}</p>}
 <div className="config-workbench"><section className="code-workspace"><div className="code-toolbar"><label>Wersja <select aria-label="Wersja konfiguracji" value={versionId||config.versions[0]?.id||''} onChange={e=>setVersionId(e.target.value)}>{config.versions.map(v=><option key={v.id} value={v.id}>v{v.version} · {formatDate(v.createdAt,true)}</option>)}</select></label><div className="row-actions">{hasPermission(user,'config.download')&&<><Button variant="ghost" disabled={detail.loading} onClick={async()=>{try{await navigator.clipboard.writeText(config.content);setNotice('Skopiowano treść konfiguracji.');}catch{setNotice('Zaznacz tekst i skopiuj ręcznie.');}}}><Copy size={15}/>Kopiuj</Button><a className="button button-secondary" href={`/api/configs/${id}/download${versionId?'?versionId='+versionId:''}`} download><Download size={15}/>Pobierz</a></>}</div></div><pre className="config-code" tabIndex={0}>{config.content||'Brak zapisanej treści.'}</pre></section><aside className="revision-rail"><h2>Historia wersji</h2><ol>{config.versions.map(v=><li key={v.id}><button type="button" onClick={()=>setVersionId(v.id)}><strong>Wersja {v.version}</strong><span>{formatDate(v.createdAt,true)}</span><small>{v.author}</small><p>{v.releaseNotes||'Zapis konfiguracji'}</p></button></li>)}</ol></aside></div>
 </>:<><div className="toolbar"><div className="toolbar-search"><Search size={16}/><input aria-label="Szukaj konfiguracji" value={q} onChange={e=>setQ(e.target.value)} placeholder="Nazwa, model, producent…"/></div></div>{list.loading&&!list.data?<Loading/>:list.data?.length?<div className="library-index">{list.data.map((c,i)=><Link className="library-index-row" href={`/configs/${c.id}`} key={c.id}><span className="library-index-number">{String(i+1).padStart(2,'0')}</span><div><strong>{c.name}</strong><small>{[c.manufacturer,c.model,c.categoryName].filter(Boolean).join(' · ')||'Konfiguracja ogólna'}</small></div><span className="mono">v{c.latestVersion}</span><span>{formatDate(c.updatedAt,true)}<small>{c.author}</small></span><Download size={16}/></Link>)}</div>:!list.error&&<EmptyState title={q?'Brak pasujących konfiguracji':'Utwórz bibliotekę zespołu'} description="Dodaj konfigurację tekstową i zachowuj kolejne wersje wraz z opisem zmian." action={canEdit&&<Button onClick={()=>setEdit(true)}>Dodaj konfigurację</Button>}/>}</>}{edit&&canEdit&&<ConfigurationForm config={config??undefined} onClose={()=>setEdit(false)} onSaved={saved}/>}</>;
}
function ConfigurationForm({config,onClose,onSaved}:{config?:ConfigurationDetail;onClose:()=>void;onSaved:(config:ConfigurationDetail)=>void}){
 const {user,lookups}=useApp(),[form,setForm]=useState({name:config?.name??'',categoryId:config?.categoryId??'',manufacturer:config?.manufacturer??'',model:config?.model??'',description:config?.description??'',content:config?.content??'',releaseNotes:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),request=useRef<{signature:string;id:string}|null>(null),lock=useRef(false);
 const update=(key:keyof typeof form,value:string)=>setForm(f=>({...f,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const body={...form,categoryId:form.categoryId||null,...(config?{version:config.latestVersion}:{})},signature=JSON.stringify(body);if(request.current?.signature!==signature)request.current={signature,id:createUuid()};onSaved(await api<ConfigurationDetail>(config?`/api/configs/${config.id}`:'/api/configs',{method:config?'PATCH':'POST',body:JSON.stringify({...body,requestId:request.current.id})},user.csrfToken));}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 return <Modal wide title={config?'Nowa wersja konfiguracji':'Dodaj konfigurację'} onClose={()=>{if(!busy)onClose();}}><form onSubmit={submit}><ErrorMessage message={error}/><fieldset className="plain-fieldset" disabled={busy}><div className="form-grid"><Field label="Nazwa *"><input required minLength={2} maxLength={200} value={form.name} onChange={e=>update('name',e.target.value)}/></Field><Field label="Typ urządzenia"><select value={form.categoryId} onChange={e=>update('categoryId',e.target.value)}><option value="">Konfiguracja ogólna</option>{lookups?.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Producent"><input maxLength={120} value={form.manufacturer} onChange={e=>update('manufacturer',e.target.value)}/></Field><Field label="Model"><input maxLength={160} value={form.model} onChange={e=>update('model',e.target.value)}/></Field></div><Field label="Opis"><textarea maxLength={2000} value={form.description} onChange={e=>update('description',e.target.value)}/></Field><Field label="Treść konfiguracji *" hint="Tekst UTF-8, do 256 KB. Kolejny zapis zachowuje poprzednią wersję."><textarea className="config-editor" spellCheck={false} required maxLength={262144} value={form.content} onChange={e=>update('content',e.target.value)}/></Field><Field label="Wczytaj plik tekstowy"><input type="file" accept=".txt,.cfg,.conf,.json,.xml,.yaml,.yml,.md" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>262144){setError('Plik może mieć do 256 KB.');return;}update('content',await file.text());}}/></Field><Field label="Opis zmian"><textarea maxLength={2000} value={form.releaseNotes} onChange={e=>update('releaseNotes',e.target.value)}/></Field></fieldset><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Anuluj</Button><Button disabled={busy}>{busy?'Zapisywanie…':'Zapisz wersję'}</Button></div></form></Modal>;
}
export function DocumentsScreen({assetId,compact=false}:{assetId?:string;compact?:boolean}){
 const {user}=useApp(),params=useSearchParams(),[q,setQ]=useState(''),[upload,setUpload]=useState(false),[success,setSuccess]=useState(''),[document,setDocument]=useState<EquipmentDocument|null>(null),[previewError,setPreviewError]=useState(''),resource=useResource<LibraryDocument[]>(`/api/documents?q=${encodeURIComponent(q)}${assetId?'&assetId='+assetId:''}`),selected=params.get('selected');
 useEffect(()=>{const id=params.get('equipmentDocument');if(!id||compact)return;let current=true;api<EquipmentDocument>('/api/equipment-documents/'+id).then(d=>{if(current)setDocument(d);}).catch(e=>{if(current)setPreviewError(e.message);});return()=>{current=false;};},[params,compact]);
 return <>{!compact&&<PageHeader eyebrow="ITH // DOCUMENTS" title="Dokumenty zespołu" description="Pliki techniczne, faktury i zachowane dokumenty wyposażenia pracowników oraz stołów." actions={hasPermission(user,'document.upload')&&<Button onClick={()=>setUpload(true)}><Upload size={16}/>Dodaj dokument</Button>}/>}<SuccessMessage message={success}/><ErrorMessage message={resource.error||previewError} onRetry={resource.reload}/>{compact?<div className="panel-heading"><h2>Pliki urządzenia</h2>{hasPermission(user,'document.upload')&&<Button variant="secondary" onClick={()=>setUpload(true)}>Dodaj plik</Button>}</div>:<div className="toolbar"><div className="toolbar-search"><Search size={16}/><input aria-label="Szukaj dokumentów" value={q} onChange={e=>setQ(e.target.value)} placeholder="Nazwa pliku…"/></div></div>}{resource.loading&&!resource.data?<Loading compact={compact}/>:resource.data?.length?<div className="document-index">{resource.data.map(d=><div className={`document-index-row ${selected===d.id?'selected':''}`} key={d.id}><FileText size={20}/><div><strong>{d.name}</strong><small>{d.equipmentDocument?'Zapis wyposażenia':Math.ceil(d.size/1024)+' KB'} · {d.equipmentDocument?'Dokument do podpisu':d.invoiceId?'Faktura':'Dokument techniczny'} · {formatDate(d.createdAt,true)} · {d.author}</small></div><>{d.equipmentDocument?<Button variant="secondary" onClick={async()=>{try{setPreviewError('');setDocument(await api<EquipmentDocument>('/api/equipment-documents/'+d.id));}catch(e){setPreviewError((e as Error).message);}}}>Podgląd / wydruk</Button>:<a className="button button-secondary" href={d.invoiceId?`/api/invoices/${d.invoiceId}/documents/${d.id}`:`/api/documents/${d.id}`} download><Download size={15}/>Pobierz</a>}</></div>)}</div>:!resource.error&&<EmptyState title={q?'Brak pasujących dokumentów':'Brak plików'} description="Dodaj dokument PDF lub plik tekstowy z instrukcją techniczną."/>}{document&&<DocumentPreview document={document} onClose={()=>setDocument(null)}/>} {upload&&<DocumentUpload assetId={assetId} onClose={()=>setUpload(false)} onSaved={()=>{setUpload(false);setSuccess('Dodano dokument.');resource.reload();}}/>}</>;
}
function DocumentUpload({assetId,onClose,onSaved}:{assetId?:string;onClose:()=>void;onSaved:()=>void}){
 const {user}=useApp(),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),request=useRef(createUuid());
 async function submit(e:FormEvent){e.preventDefault();if(!file||busy)return;setBusy(true);setError('');try{await api(`/api/documents?requestId=${request.current}${assetId?'&assetId='+assetId:''}`,{method:'POST',body:file,headers:{'Content-Type':'application/octet-stream','X-File-Name':encodeURIComponent(file.name)}},user.csrfToken);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title="Dodaj dokument" onClose={()=>{if(!busy)onClose();}}><form onSubmit={submit}><ErrorMessage message={error}/><Field label="Plik PDF lub tekstowy *" hint="PDF do 10 MB. Pliki tekstowe UTF-8 do 256 KB."><input type="file" required accept=".pdf,.txt,.md,.json,.cfg,.conf,.xml,.yaml,.yml,.log" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]??null);request.current=createUuid();}}/></Field><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Anuluj</Button><Button disabled={busy||!file}>{busy?'Przesyłanie…':'Dodaj dokument'}</Button></div></form></Modal>;
}
