'use client';
import {createUuid} from '@/shared/uuid';
import {useRef,useState} from 'react';
import Link from 'next/link';
import type {Asset,InvoiceDetail,InvoiceLine,PageResult} from '@/shared/types';
import type {SerialMatch,SerialPreview} from '@/shared/purchase';
import {serialList} from '@/shared/purchase';
import {useApp} from './context';
import {SearchSelect} from './pickers';
import {api,Button,ErrorMessage,Field,Modal} from './ui';
const findCards=async(text:string,signal:AbortSignal)=>(await api<PageResult<Asset>>(`/api/assets?q=${encodeURIComponent(text)}&pageSize=25`,{signal})).items.map(a=>({id:a.assetId,label:`${a.assetId} · ${a.serialNumber??'bez SN'}`,detail:a.name,serialNumber:a.serialNumber}));

export function SerialEditor({text,quantity,onChange,onConfirmed,onPreview,invoiceId,lineId}:{text:string;quantity:string|number;onChange:(text:string)=>void;onConfirmed:(matches:SerialMatch[])=>void;onPreview?:(preview:SerialPreview[]|null)=>void;invoiceId?:string;lineId?:string}){
 const {user}=useApp(),[preview,setPreview]=useState<SerialPreview[]|null>(null),[checked,setChecked]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const lock=useRef(false),[pickerKey,setPickerKey]=useState(0);const valid=preview&&checked===text;
 const cardSearch=<SearchSelect key={pickerKey} label="Dodaj numer z istniejącej karty" value="" options={[]} search={findCards} placeholder="Asset ID, nazwa lub numer seryjny…" onSelect={(id,card)=>{if(!id||!card)return;if(!card.serialNumber){setError('Ta karta nie ma numeru seryjnego. Uzupełnij SN na karcie urządzenia przed dopasowaniem.');}else if(serialList(text).some(s=>s.toLowerCase()===card.serialNumber!.toLowerCase()))setError('Ten numer jest już wpisany w tej pozycji.');else{onChange([...serialList(text),card.serialNumber].join('\n'));onConfirmed([]);onPreview?.(null);setPreview(null);setError('');}setPickerKey(k=>k+1);}}/>;
 async function inspect(){if(lock.current)return;lock.current=true;setBusy(true);setError('');onConfirmed([]);onPreview?.(null);try{const serials=serialList(text);if(serials.length>Number(quantity))throw new Error('Liczba numerów przekracza ilość pozycji.');const result=await api<SerialPreview[]>('/api/invoices/serial-preview',{method:'POST',body:JSON.stringify({serialNumbers:serials,invoiceId,lineId})},user.csrfToken);setPreview(result);onPreview?.(result);setChecked(text);}catch(e){setPreview(null);setError((e as Error).message);}finally{setBusy(false);lock.current=false;}}
 return <div className="serial-editor">{cardSearch}<Field label="Numery seryjne" hint={`${quantity} urządzeń w pozycji. Wklej po jednym numerze w wierszu; nieznane można utworzyć przy przyjęciu, brakujące uzupełnić później.`}><textarea aria-label="Numery seryjne" maxLength={161000} value={text} onChange={e=>{onChange(e.target.value);onConfirmed([]);setPreview(null);}} placeholder={'HP-DEMO-001\nHP-DEMO-002'}/></Field><ErrorMessage message={error}/><Button type="button" variant="secondary" disabled={busy||!text.trim()} onClick={inspect}>{busy?'Sprawdzanie…':'Sprawdź numery w bazie'}</Button>{valid&&<><ul className="serial-results">{preview.map(p=><li key={p.serialNumber}><span className="mono">{p.serialNumber}</span><span>{p.state==='new'?'Nowe urządzenie':p.state==='linked'?'Już powiązane z tą pozycją':p.state==='conflict'?`Konflikt — FV ${p.invoiceNumber??'inna pozycja'}`:'Istnieje — do powiązania'}{p.assetId&&<> · <Link href={'/asset/'+p.assetId} target="_blank">{p.assetId}</Link> · {p.name}</>}</span></li>)}</ul>{preview.some(p=>p.state==='existing')&&!preview.some(p=>p.state==='conflict')&&<Button type="button" variant="secondary" onClick={()=>onConfirmed(preview.filter(p=>p.state==='existing').map(p=>({serialNumber:p.serialNumber,assetId:p.assetId!,version:p.version!})))}>Potwierdź powiązanie istniejących urządzeń</Button>}{preview.some(p=>p.state==='conflict')&&<p className="notice notice-error">Popraw konflikty przed zapisem. Istniejące powiązania nie zostaną nadpisane.</p>}</>}</div>;
}
export function InvoiceSerialModal({invoice,line,onClose,onSaved}:{invoice:InvoiceDetail;line:InvoiceLine;onClose:()=>void;onSaved:()=>void}){
 const {user}=useApp(),[text,setText]=useState((line.serialNumbers??[]).join('\n')),[matches,setMatches]=useState<SerialMatch[]>([]),[createMissing,setCreateMissing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const request=useRef<{signature:string;id:string}|null>(null),lock=useRef(false);
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const body={serialNumbers:serialList(text),matches,createMissing,version:invoice.version};const signature=JSON.stringify(body);if(request.current?.signature!==signature)request.current={signature,id:createUuid()};await api(`/api/invoices/${invoice.id}/items/${line.id}/serials`,{method:'POST',body:JSON.stringify({...body,requestId:request.current.id})},user.csrfToken);onSaved();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 return <Modal title={`Urządzenia — pozycja ${line.position??''}: ${line.name}`} wide onClose={()=>{if(!busy)onClose();}}><ErrorMessage message={error}/><fieldset disabled={busy} className="plain-fieldset"><SerialEditor text={text} quantity={line.quantity} onChange={setText} onConfirmed={setMatches} invoiceId={invoice.id} lineId={line.id}/>{matches.length>0&&<p className="help-note">Potwierdzono {matches.length} istniejących urządzeń. Zachowają stan, lokalizację, odbiorcę i wcześniejszą cenę zakupu.</p>}<label className="checkbox-inline"><input type="checkbox" checked={createMissing} onChange={e=>setCreateMissing(e.target.checked)}/>Utwórz i przyjmij nieznane numery jako nowe urządzenia</label><p className="help-note">Nowe karty otrzymają kategorię i dane zapisane przy pozycji. Zapis samych numerów pozwala dokończyć powiązania później.</p></fieldset><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Anuluj</Button><Button disabled={busy||!text.trim()} onClick={save}>{busy?'Zapisywanie…':'Zapisz powiązania'}</Button></div></Modal>;
}
