'use client';
import {createUuid} from '@/shared/uuid';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {ArrowLeft,Check,Download,Plus,ScanLine} from 'lucide-react';
import type {InventoryScan,InventoryScanDetail,InventoryEvent} from '@/shared/product';
import {hasPermission} from '@/shared/permissions';
import {useApp} from './context';
import {LocationPicker} from './pickers';
import {useIdentifierQueue} from './identifier-queue';
import {api,Button,EmptyState,ErrorMessage,formatDate,Loading,Modal,PageHeader,useResource} from './ui';

export function StocktakesScreen({id}:{id?:string}){
 const {user}=useApp(),router=useRouter(),params=useSearchParams();const [start,setStart]=useState(params.get('start')==='1'),[locationId,setLocationId]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState<{result:string;code:string}|null>(null),[confirm,setConfirm]=useState(false),[continuous,setContinuous]=useState(true);
 const list=useResource<InventoryScan[]>(!id?'/api/stocktakes':null),detail=useResource<InventoryScanDetail>(id?`/api/stocktakes/${id}`:null),[live,setLive]=useState<InventoryScanDetail|null>(null),scan=live??detail.data,input=useRef<HTMLInputElement>(null),lock=useRef(false),pending=useRef<{signature:string;id:string}|null>(null);
 useEffect(()=>{if(params.get('start')==='1')setStart(true);},[params]);
 const currentScan=useRef<InventoryScanDetail|null>(scan);
 useEffect(()=>{currentScan.current=scan;},[scan]);
 const request=(signature:string)=>{if(pending.current?.signature!==signature)pending.current={signature,id:createUuid()};return pending.current.id;};
 async function create(e:FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const value=await api<InventoryScanDetail>('/api/stocktakes',{method:'POST',body:JSON.stringify({locationId,requestId:request('start:'+locationId)})},user.csrfToken);pending.current=null;setStart(false);setLive(null);router.push(`/stocktakes/${value.id}`);}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 const queue=useIdentifierQueue((value,requestId)=>api<{scan:InventoryScan;event:InventoryEvent}>(`/api/stocktakes/${id}/scan`,{method:'POST',body:JSON.stringify({code:value,requestId})},user.csrfToken),(value,scanned)=>{const current=currentScan.current;if(!current||value.scan.version>current.version+1){currentScan.current=null;setLive(null);detail.reload();}else if(value.scan.version>=current.version){const next={...current,...value.scan,events:[value.event,...current.events.filter(e=>e.id!==value.event.id)].slice(0,100),missingItems:current.missingItems.filter(a=>a.assetId!==value.event.assetId)};currentScan.current=next;setLive(next);}setFeedback({result:value.event.result,code:scanned});if(continuous)input.current?.focus();});
 function observe(e:FormEvent){e.preventDefault();if(!id||busy||!queue.enqueue(code))return;setCode('');if(continuous)input.current?.focus();}
 async function finish(){if(!scan||busy||queue.queued||queue.busy)return;setBusy(true);setError('');try{setLive(await api<InventoryScanDetail>(`/api/stocktakes/${id}/finish`,{method:'POST',body:JSON.stringify({version:scan.version})},user.csrfToken));setConfirm(false);}catch(e){setError((e as Error).message);detail.reload();setLive(null);}finally{setBusy(false);}}
 if(!hasPermission(user,'inventory.run'))return <ErrorMessage message="Brak uprawnienia do inwentaryzacji."/>;
 const resultLabels:Record<string,string>={EXPECTED:'Potwierdzono urządzenie',UNEXPECTED:'Urządzenie spoza wybranej lokalizacji',UNKNOWN:'Nieznany kod',DUPLICATE:'Powtórzony odczyt'};
 return <>{id&&<Link className="back-link" href="/stocktakes"><ArrowLeft size={15}/>Sesje inwentaryzacji</Link>}<PageHeader eyebrow="ITH // INVENTORY CHECK" title={id?scan?.locationName??'Inwentaryzacja':'Inwentaryzacja sprzętu'} description={id?'Oczekiwana lista pochodzi z chwili rozpoczęcia sesji. Odczyt nie zmienia lokalizacji ani przypisania urządzenia.':'Wybierz lokalizację, odczytaj identyfikatory i zachowaj raport braków oraz różnic.'} actions={!id?<Button onClick={()=>setStart(true)}><Plus size={16}/>Rozpocznij inwentaryzację</Button>:scan&&<><a className="button button-secondary" download href={`/api/stocktakes/${id}/export`}><Download size={16}/>Raport CSV</a>{scan.status==='OPEN'&&<Button onClick={()=>setConfirm(true)} disabled={busy||queue.busy||queue.queued>0}><Check size={16}/>Zakończ i zapisz raport</Button>}</>}/><ErrorMessage message={error||list.error||detail.error} onRetry={()=>{setLive(null);list.reload();detail.reload();}}/>{id?detail.loading&&!scan?<Loading/>:scan&&<>
 <div className="stocktake-context"><span className={`status-light ${scan.status==='OPEN'?'pending':'success'}`}/><strong>{scan.status==='OPEN'?'SESJA OTWARTA':'RAPORT ZAPISANY'}</strong><span>{formatDate(scan.startedAt,true)} · {scan.startedBy}</span>{scan.completedAt&&<span>Zakończono {formatDate(scan.completedAt,true)}</span>}</div>
 <div className="inventory-counters">{[['Oczekiwane',scan.expected],['Odczytane',scan.observed],['Brakujące',scan.missing],['Nieoczekiwane',scan.unexpected],['Duplikaty',scan.duplicates],['Nieznane',scan.unknown]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
 {scan.status==='OPEN'&&<section className="stocktake-reader"><div><ScanLine size={28}/><h2>Odczyt urządzeń</h2><p>Czytnik HID / USB / RFID może wpisywać identyfikator i kończyć go klawiszem Enter. Każdy zatwierdzony odczyt jest zapisywany.</p></div><form onSubmit={observe}><input ref={input} autoFocus aria-label="Odczytaj kod inwentaryzacji" maxLength={2048} autoComplete="off" spellCheck={false} value={code} onChange={e=>setCode(e.target.value)} placeholder="Asset ID, serial, RFID lub QR"/><Button disabled={busy||!code.trim()}>Zapisz odczyt</Button></form><ErrorMessage message={queue.error} onRetry={queue.retry}/>{queue.failedCode&&<div className="queue-failure"><span>Odczyt oczekujący: {queue.failedCode}</span><Button variant="secondary" onClick={queue.skip} disabled={queue.busy}>Pomiń ten niezapisany odczyt</Button></div>}<div className="queue-status" role="status">{queue.queued?`Pozostało do zapisania: ${queue.queued}`:'Wszystkie odczyty zapisane'}</div><label className="checkbox-inline"><input type="checkbox" checked={continuous} onChange={e=>setContinuous(e.target.checked)}/>Odczyt ciągły — pozostaw pole gotowe na kolejny skan</label>{feedback&&<div className={`scan-feedback result-${feedback.result.toLowerCase()}`} role="status"><strong>{resultLabels[feedback.result]}</strong><span className="mono">{feedback.code}</span></div>}</section>}
 <div className="stocktake-results"><section><div className="section-heading"><h2>Brakujące urządzenia</h2><span>{scan.missingItems.length}</span></div>{scan.missingItems.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Urządzenie</th><th>Asset ID</th><th>Numer seryjny</th></tr></thead><tbody>{scan.missingItems.map(a=><tr key={a.id}><td><Link href={`/asset/${a.assetId}`}>{a.name}</Link></td><td className="mono">{a.assetId}</td><td className="mono">{a.serialNumber||'—'}</td></tr>)}</tbody></table></div>:<EmptyState title="Wszystkie oczekiwane urządzenia odczytane" description="Sprawdź również odczyty nieoczekiwane i nieznane przed zamknięciem raportu."/>}</section><section><div className="section-heading"><h2>Ostatnie odczyty</h2><span>{scan.events.length}</span></div>{scan.events.length?<ol className="scan-event-list">{scan.events.slice(0,100).map(e=><li className={`result-${e.result.toLowerCase()}`} key={e.id}><span className="status-light"/><div><strong>{e.name||e.code}</strong><small>{resultLabels[e.result]} · {e.assetId??e.code}</small></div><time>{formatDate(e.createdAt,true)}</time></li>)}</ol>:<EmptyState title="Gotowe do odczytu" description="Pierwszy zeskanowany kod pojawi się tutaj."/>}</section></div>
 </>:list.loading&&!list.data?<Loading/>:list.data?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Lokalizacja / data</th><th>Status</th><th>Odczytane</th><th>Brakujące</th><th>Operator</th><th/></tr></thead><tbody>{list.data.map(s=><tr key={s.id}><td><Link className="table-title" href={`/stocktakes/${s.id}`}>{s.locationName}</Link><small>{formatDate(s.startedAt,true)}</small></td><td>{s.status==='OPEN'?'Otwarta':s.status==='COMPLETED'?'Raport zapisany':'Anulowana'}</td><td>{s.observed} / {s.expected}</td><td>{s.missing}</td><td>{s.startedBy}</td><td><Link className="text-link" href={`/stocktakes/${s.id}`}>Otwórz sesję</Link></td></tr>)}</tbody></table></div>:!list.error&&<EmptyState title="Pierwsza kontrola wyposażenia" description="Rozpocznij sesję dla lokalizacji. System zachowa listę oczekiwanego sprzętu i raport wynikowy."/>}
 {start&&<Modal title="Rozpocznij inwentaryzację" onClose={()=>{if(!busy)setStart(false);}}><form onSubmit={create}><ErrorMessage message={error}/><LocationPicker required label="Lokalizacja do sprawdzenia *" value={locationId} onChange={setLocationId}/><p className="help-note">Lista obejmie aktywne urządzenia tej lokalizacji i wszystkich folderów podrzędnych. Każdy skan porównamy z tą listą.</p><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={()=>setStart(false)}>Anuluj</Button><Button disabled={busy||!locationId}>{busy?'Przygotowywanie…':'Rozpocznij sesję'}</Button></div></form></Modal>}
 {confirm&&scan&&<Modal title="Zapisz końcowy raport" onClose={()=>{if(!busy)setConfirm(false);}}><p>Odczytano {scan.observed} z {scan.expected} oczekiwanych urządzeń. Brakujących: {scan.missing}. Nieoczekiwanych: {scan.unexpected}. Nieznanych kodów: {scan.unknown}.</p><p className="help-note">Po zakończeniu nie dodasz kolejnych odczytów do tej sesji. Raport pozostanie dostępny do pobrania.</p><ErrorMessage message={error}/><div className="form-actions"><Button variant="secondary" disabled={busy} onClick={()=>setConfirm(false)}>Kontynuuj odczyty</Button><Button disabled={busy||queue.busy||queue.queued>0} onClick={finish}>Zakończ i zapisz</Button></div></Modal>}</>;
}
