'use client';
import {defaultTerminalConfig,terminalConfig,terminalAssetFieldLabels,terminalInventoryFieldLabels,terminalCounterLabels,type DeviceConfig,type TerminalConfig} from '@/shared/devices';
import {TerminalReadingCard} from './terminal-reading';
import {Button,Field} from './ui';

export function TerminalEditor({config,onChange}:{config:DeviceConfig;onChange:(config:DeviceConfig)=>void}){
 const options=terminalConfig(config);
 function update<K extends keyof TerminalConfig>(key:K,value:TerminalConfig[K]){onChange({...config,scanner:{...options,[key]:value}});}
 function toggle<K extends 'assetFields'|'inventoryFields'|'counters'>(key:K,value:TerminalConfig[K][number]){const current=options[key] as string[];update(key,(current.includes(value)?current.filter(item=>item!==value):[...current,value]) as TerminalConfig[K]);}
 return <section className="tv-editor terminal-editor"><h2>Ekran terminala</h2><p className="help-note">Wybierz dane potrzebne operatorowi. Wyłączone pola wyniku i liczniki nie są przesyłane do terminala.</p>
 <div className="tv-presets"><span>Układ:</span><Button type="button" variant="secondary" onClick={()=>onChange({...config,scanner:{...options,assetFields:['assetId','status','locationName'],inventoryFields:['sku','stock'],showCode:false,showHistory:false,showCamera:false,textSize:'large'}})}>Zwięzły · czytnik w terminalu</Button><Button type="button" variant="secondary" onClick={()=>onChange({...config,scanner:{...defaultTerminalConfig(),inputLabel:options.inputLabel,inputPlaceholder:options.inputPlaceholder}})}>Pełny wynik i historia</Button></div>
 <fieldset className="tv-option-group"><legend>Dane urządzenia po odczycie</legend><div className="tv-check-grid">{Object.entries(terminalAssetFieldLabels).map(([key,label])=><label className="checkbox-inline" key={key}><input type="checkbox" aria-label={'Terminal: '+label} checked={options.assetFields.includes(key as keyof typeof terminalAssetFieldLabels)} onChange={()=>toggle('assetFields',key as keyof typeof terminalAssetFieldLabels)}/>{label}</label>)}</div><small>Nazwa rekordu jest zawsze widoczna.</small></fieldset>
 {config.mode!=='INVENTORY'&&<fieldset className="tv-option-group"><legend>Dane produktu magazynowego po odczycie</legend><div className="tv-check-grid">{Object.entries(terminalInventoryFieldLabels).map(([key,label])=><label className="checkbox-inline" key={key}><input type="checkbox" aria-label={'Produkt na terminalu: '+label} checked={options.inventoryFields.includes(key as keyof typeof terminalInventoryFieldLabels)} onChange={()=>toggle('inventoryFields',key as keyof typeof terminalInventoryFieldLabels)}/>{label}</label>)}</div></fieldset>}
 {config.mode==='INVENTORY'&&<fieldset className="tv-option-group"><legend>Liczniki inwentaryzacji</legend><div className="tv-check-grid">{Object.entries(terminalCounterLabels).map(([key,label])=><label className="checkbox-inline" key={key}><input type="checkbox" checked={options.counters.includes(key as keyof typeof terminalCounterLabels)} onChange={()=>toggle('counters',key as keyof typeof terminalCounterLabels)}/>{label}</label>)}</div><small>Puste zaznaczenie ukrywa wszystkie liczniki. Wyniki spisu pozostają w raporcie.</small></fieldset>}
 <div className="device-module-options"><label className="checkbox-inline"><input type="checkbox" checked={options.showCode} onChange={e=>update('showCode',e.target.checked)}/>Pokaż odczytany kod w wyniku i historii</label><label className="checkbox-inline"><input type="checkbox" checked={options.showCamera} onChange={e=>update('showCamera',e.target.checked)}/>Przycisk skanowania aparatem</label><label className="checkbox-inline"><input type="checkbox" checked={options.showHistory} onChange={e=>update('showHistory',e.target.checked)}/>Historia odczytów na tym ekranie</label></div>
 <div className="form-grid"><Field label="Wielkość tekstu na terminalu"><select value={options.textSize} onChange={e=>update('textSize',e.target.value as TerminalConfig['textSize'])}><option value="standard">Standardowa</option><option value="large">Duża · obsługa w magazynie</option></select></Field>{options.showHistory&&<Field label="Widoczne ostatnie odczyty"><select value={options.historyLimit} onChange={e=>update('historyLimit',Number(e.target.value))}>{Array.from(new Set([5,10,20,50,100,options.historyLimit])).sort((a,b)=>a-b).map(limit=><option key={limit} value={limit}>{limit} odczytów</option>)}</select></Field>}<Field label="Opis pola skanowania"><input required maxLength={120} value={options.inputLabel} onChange={e=>update('inputLabel',e.target.value)}/></Field><Field label="Podpowiedź w polu skanowania"><input required maxLength={160} value={options.inputPlaceholder} onChange={e=>update('inputPlaceholder',e.target.value)}/></Field></div>
 <div className="terminal-editor-preview" data-terminal-size={options.textSize}><small>PODGLĄD · przykładowe dane</small><p>{options.inputLabel}</p><div className="terminal-preview-input">{options.inputPlaceholder}</div><TerminalReadingCard options={options} reading={{code:'DEMO-QR-308A',title:'Przykładowy monitor',asset:{name:'Przykładowy monitor',assetId:'ITHW-00000001',serialNumber:'DEMO-SN-001',model:'Model demonstracyjny',status:'AVAILABLE',locationName:'Magazyn / Stół 308A'}}}/></div>
 </section>;
}
