'use client';
import {ArrowUp,ArrowDown} from 'lucide-react';
import {incidentPriorityLabels,incidentStatusLabels,type IncidentPriority,type IncidentStatus} from '@/shared/product';
import {tvDashboard,tvMetricLabels,tvIncidentFieldLabels,tvSectionLabels,type DeviceConfig,type TvDashboardConfig} from '@/shared/devices';
import {useApp} from './context';
import {Button,Field} from './ui';

export function TvDashboardEditor({config,onChange}:{config:DeviceConfig;onChange:(config:DeviceConfig)=>void}){
 const {lookups}=useApp(),options=tvDashboard(config),showIncidentList=config.mode==='INCIDENTS'||config.mode==='OVERVIEW'&&config.showIncidents,needIncidentFilters=showIncidentList||config.mode==='OVERVIEW'&&config.showStats&&options.metrics.some(key=>key==='openIncidents'||key==='criticalIncidents');
 function update<K extends keyof TvDashboardConfig>(key:K,value:TvDashboardConfig[K]){onChange({...config,tv:{...options,[key]:value}});}
 function toggle<K extends 'metrics'|'incidentStatuses'|'incidentPriorities'|'incidentFields'>(key:K,value:TvDashboardConfig[K][number]){const current=options[key] as string[];update(key,(current.includes(value)?current.filter(item=>item!==value):[...current,value]) as TvDashboardConfig[K]);}
 function moveMetric(index:number,direction:number){const next=[...options.metrics];[next[index],next[index+direction]]=[next[index+direction],next[index]];update('metrics',next);}
 function move(index:number,direction:number){const next=[...options.sectionOrder];[next[index],next[index+direction]]=[next[index+direction],next[index]];update('sectionOrder',next);}
 return <section className="tv-editor"><h2>Dane dashboardu TV</h2><p className="help-note">Ustawienia dotyczą wyłącznie tego TV. Zapisane zmiany pojawią się automatycznie na ekranie.</p>
 <div className="tv-presets"><span>Rozpocznij od:</span><Button type="button" variant="secondary" onClick={()=>onChange({...config,mode:'OVERVIEW',showStats:true,showIncidents:true})}>Liczniki i zgłoszenia</Button><Button type="button" variant="secondary" onClick={()=>onChange({...config,mode:'INCIDENTS',showStats:false,showIncidents:true})}>Tylko zgłoszenia</Button><Button type="button" variant="secondary" onClick={()=>onChange({...config,mode:'OVERVIEW',showStats:true,showIncidents:false})}>Tylko liczniki</Button><Button type="button" variant="secondary" onClick={()=>onChange({...config,mode:'MESSAGE'})}>Tylko komunikat</Button></div>
 {config.mode!=='MESSAGE'&&<><div className="form-grid"><Field label="Kategoria sprzętu na TV"><select value={options.categoryId??''} onChange={e=>update('categoryId',e.target.value||null)}><option value="">Wszystkie kategorie</option>{lookups?.categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><label className="checkbox-inline"><input type="checkbox" checked={options.includeChildren} onChange={e=>update('includeChildren',e.target.checked)}/>Uwzględniaj podfoldery wybranej lokalizacji</label></div>
 {config.mode==='OVERVIEW'&&config.showStats&&<fieldset className="tv-option-group"><legend>Widoczne liczniki</legend><div className="tv-check-grid">{Object.entries(tvMetricLabels).map(([key,label])=><label className="checkbox-inline" key={key}><input type="checkbox" aria-label={'Licznik: '+label} checked={options.metrics.includes(key as keyof typeof tvMetricLabels)} onChange={()=>toggle('metrics',key as keyof typeof tvMetricLabels)}/>{label}</label>)}</div><details className="tv-layout-details"><summary>Kolejność liczników</summary><ol className="tv-section-order">{options.metrics.map((metric,index)=><li key={metric}><strong>{tvMetricLabels[metric]}</strong><button type="button" className="icon-button" aria-label={'Przesuń licznik '+tvMetricLabels[metric]+' w górę'} disabled={index===0} onClick={()=>moveMetric(index,-1)}><ArrowUp size={16}/></button><button type="button" className="icon-button" aria-label={'Przesuń licznik '+tvMetricLabels[metric]+' w dół'} disabled={index===options.metrics.length-1} onClick={()=>moveMetric(index,1)}><ArrowDown size={16}/></button></li>)}</ol></details></fieldset>}
 {needIncidentFilters&&<><fieldset className="tv-option-group"><legend>Statusy zgłoszeń na TV</legend><div className="tv-check-grid">{Object.entries(incidentStatusLabels).map(([key,label])=><label className="checkbox-inline" key={key}><input type="checkbox" checked={options.incidentStatuses.includes(key as IncidentStatus)} onChange={()=>toggle('incidentStatuses',key as IncidentStatus)}/>{label}</label>)}</div></fieldset><fieldset className="tv-option-group"><legend>Priorytety zgłoszeń na TV</legend><div className="tv-check-grid">{Object.entries(incidentPriorityLabels).map(([key,label])=><label className="checkbox-inline" key={key}><input type="checkbox" checked={options.incidentPriorities.includes(key as IncidentPriority)} onChange={()=>toggle('incidentPriorities',key as IncidentPriority)}/>{label}</label>)}</div></fieldset>{showIncidentList&&<><fieldset className="tv-option-group"><legend>Pola widoczne w zgłoszeniu</legend><div className="tv-check-grid">{Object.entries(tvIncidentFieldLabels).map(([key,label])=><label className="checkbox-inline" key={key}><input type="checkbox" checked={options.incidentFields.includes(key as keyof typeof tvIncidentFieldLabels)} onChange={()=>toggle('incidentFields',key as keyof typeof tvIncidentFieldLabels)}/>{label}</label>)}</div><small>Tytuł zgłoszenia jest zawsze widoczny. Wyłączone pola nie są przesyłane do TV.</small></fieldset><div className="form-grid"><Field label="Maksymalna liczba zgłoszeń"><input type="number" required min={1} max={50} value={options.incidentLimit} onChange={e=>update('incidentLimit',Number(e.target.value))}/></Field><Field label="Kolejność zgłoszeń"><select value={options.incidentSort} onChange={e=>update('incidentSort',e.target.value as TvDashboardConfig['incidentSort'])}><option value="priority">Najpierw pilne, potem ostatnio zmienione</option><option value="newest">Ostatnio zmienione</option><option value="oldest">Najdłużej bez aktualizacji</option></select></Field></div></>}</>}
 </>}
 <details className="tv-layout-details" open><summary>Wygląd i kolejność sekcji</summary><div className="form-grid"><Field label="Kolumny zgłoszeń"><select value={options.columns} onChange={e=>update('columns',Number(e.target.value) as 1|2|3)}><option value={1}>1 — szeroka lista</option><option value={2}>2 — dwa bloki</option><option value={3}>3 — trzy bloki</option></select></Field><Field label="Wielkość tekstu na TV"><select value={options.textSize} onChange={e=>update('textSize',e.target.value as TvDashboardConfig['textSize'])}><option value="standard">Standardowa</option><option value="large">Duża</option><option value="xlarge">Bardzo duża</option></select></Field><Field label="Zgłoszenia na jednej stronie"><input type="number" required min={1} max={12} value={options.pageSize} onChange={e=>update('pageSize',Number(e.target.value))}/></Field><Field label="Zmień stronę zgłoszeń co (sekundy)"><input type="number" required min={10} max={120} value={options.rotateSeconds} onChange={e=>update('rotateSeconds',Number(e.target.value))}/></Field></div><label className="checkbox-inline"><input type="checkbox" checked={options.showClock} onChange={e=>update('showClock',e.target.checked)}/>Pokaż zegar na ekranie</label><ol className="tv-section-order">{options.sectionOrder.map((section,index)=><li key={section}><strong>{tvSectionLabels[section]}</strong><button type="button" className="icon-button" aria-label={'Przesuń '+tvSectionLabels[section]+' w górę'} disabled={index===0} onClick={()=>move(index,-1)}><ArrowUp size={16}/></button><button type="button" className="icon-button" aria-label={'Przesuń '+tvSectionLabels[section]+' w dół'} disabled={index===2} onClick={()=>move(index,1)}><ArrowDown size={16}/></button></li>)}</ol></details>
 <div className="tv-layout-preview" aria-label="Podgląd kolejności sekcji"><small>PODGLĄD UKŁADU · dane pojawią się na TV po zapisie</small>{options.sectionOrder.map(section=>section==='message'?config.message&&<div key={section} className="tv-preview-message">{config.message}</div>:section==='statistics'?config.mode==='OVERVIEW'&&config.showStats&&<div key={section} className="tv-preview-metrics">{options.metrics.map(key=><span key={key}><strong>—</strong>{tvMetricLabels[key]}</span>)}</div>:(config.mode==='INCIDENTS'||config.mode==='OVERVIEW'&&config.showIncidents)&&<div key={section} className="tv-preview-incidents"><strong>Zgłoszenia · {options.columns} kolumny</strong><span>{options.incidentFields.map(key=>tvIncidentFieldLabels[key]).join(' · ')||'Tylko tytuł'}</span></div>)}</div>
 </section>;
}
