'use client';
import {useEffect,useState,type CSSProperties} from 'react';
import {tvDashboard,tvMetricLabels,type DeviceScreenData} from '@/shared/devices';
import {incidentPriorityLabels,incidentStatusLabels} from '@/shared/product';
import {formatDate} from './ui';

export function TvClock({enabled}:{enabled:boolean}){const [now,setNow]=useState<Date|null>(null);useEffect(()=>{if(!enabled)return;setNow(new Date());const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer);},[enabled]);return enabled&&now?<time className="tv-clock" dateTime={now.toISOString()}>{now.toLocaleTimeString('pl-PL')}</time>:null;}

export function TvDashboard({data}:{data:DeviceScreenData}){
 const options=tvDashboard(data.config),[page,setPage]=useState(0),pages=Math.max(1,Math.ceil(data.incidents.length/options.pageSize)),current=Math.min(page,pages-1);
 useEffect(()=>{setPage(0);},[data.version]);
 useEffect(()=>{if(pages<2)return;const timer=setInterval(()=>setPage(value=>(value+1)%pages),options.rotateSeconds*1000);return()=>clearInterval(timer);},[pages,options.rotateSeconds]);
 const showIncidents=data.config.mode==='INCIDENTS'||data.config.mode==='OVERVIEW'&&data.config.showIncidents;
 const message=data.config.message?<aside className={'device-notification level-'+data.config.messageLevel} role={data.config.messageLevel==='CRITICAL'?'alert':'status'}><span>{data.config.messageLevel==='CRITICAL'?'PILNE':data.config.messageLevel==='WARNING'?'WAŻNE':'KOMUNIKAT'}</span><p>{data.config.message}</p></aside>:data.config.mode==='MESSAGE'?<div className="device-message-empty">Ekran gotowy. Ustaw komunikat w panelu.</div>:null;
 const statistics=data.config.mode==='OVERVIEW'&&data.config.showStats&&data.metrics.length>0?<section className="device-tv-statistics" aria-label="Wybrane liczniki TV" style={{'--metric-columns':Math.min(6,data.metrics.length)} as CSSProperties}>{data.metrics.map(metric=><div key={metric.key} className={metric.key==='criticalIncidents'&&metric.value>0?'critical-stat':''}><strong>{metric.value}</strong><span>{tvMetricLabels[metric.key]}</span></div>)}</section>:null;
 const incidents=showIncidents?<section className="device-tv-incidents"><div className="section-heading"><h2>Zgłoszenia</h2><span>{data.incidentCount} pasujących{pages>1?` · strona ${current+1}/${pages}`:''}</span></div>{data.incidents.length?<><div className="device-incident-list" style={{'--incident-columns':options.columns} as CSSProperties}>{data.incidents.slice(current*options.pageSize,(current+1)*options.pageSize).map(incident=><article key={incident.id} className={incident.priority?'priority-'+incident.priority.toLowerCase():undefined}><div>{incident.number&&<small className="mono">{incident.number}</small>}<h3>{incident.title}</h3>{incident.assetName&&<p>{incident.assetName}</p>}</div>{(incident.priority||incident.status||incident.updatedAt)&&<div>{incident.priority&&<span>{incidentPriorityLabels[incident.priority]}</span>}{incident.status&&<strong>{incidentStatusLabels[incident.status]}</strong>}{incident.updatedAt&&<small>{formatDate(incident.updatedAt,true)}</small>}</div>}</article>)}</div>{pages>1&&<div className="tv-page-controls"><button type="button" onClick={()=>setPage((current-1+pages)%pages)} aria-label="Poprzednia strona zgłoszeń">←</button><span>Zmiana strony co {options.rotateSeconds} s</span><button type="button" onClick={()=>setPage((current+1)%pages)} aria-label="Następna strona zgłoszeń">→</button></div>}</>:<div className="device-message-empty">Brak zgłoszeń zgodnych z filtrami.</div>}</section>:null;
 const sections={message,statistics,incidents};return <div className="tv-dashboard-sections">{options.sectionOrder.map(section=>sections[section]&&<div className={'tv-section tv-section-'+section} key={section}>{sections[section]}</div>)}</div>;
}
