'use client';
import {hasPermission} from '@/shared/permissions';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {useRouter,useSearchParams} from 'next/navigation';
import {ArrowLeft,ArrowUpRight,MapPin,Plus,Search} from 'lucide-react';
import type {Workstation,WorkstationEquipment} from '@/shared/types';
import {canEdit,useApp} from './context';
import {AssetForm} from './assets';
import {AssetLinker} from './asset-linker';
import {EquipmentDocuments} from './equipment-documents';
import {LocationPicker} from './pickers';
import {api,Button,EmptyState,ErrorMessage,Field,Loading,Modal,PageHeader,StatusBadge,useResource} from './ui';
export function WorkstationsScreen({id}:{id?:string}){return id?<StationProfile id={id}/>:<StationList/>;}
function StationList(){
 const {user,refreshLookups}=useApp(),router=useRouter(),params=useSearchParams(),resource=useResource<Workstation[]>('/api/workstations');
 const [creating,setCreating]=useState(params.get('create')==='1'),[search,setSearch]=useState(''),[name,setName]=useState(''),[parentId,setParentId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const station=await api<Workstation>('/api/workstations',{method:'POST',body:JSON.stringify({name,parentId:parentId||null})},user.csrfToken);refreshLookups();setCreating(false);router.push(`/workstations/${station.id}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(params.get('create')==='1'&&hasPermission(user,'employee.edit'))setCreating(true);},[params,user]);
 const stations=resource.data?.filter(s=>s.path.toLocaleLowerCase('pl').includes(search.toLocaleLowerCase('pl')));
 return <><PageHeader eyebrow="WYPOSAŻENIE MIEJSCA PRACY" title="Stanowiska i stoły" description="Sprzęt przypisany do miejsca, np. 308A. Bez osobistego wydania pracownikowi magazynowemu." actions={hasPermission(user,'employee.edit')&&<Button onClick={()=>setCreating(true)}><Plus size={16}/>Dodaj stanowisko</Button>}/><ErrorMessage message={resource.error} onRetry={resource.reload}/><div className="toolbar"><div className="toolbar-search"><Search size={16}/><input aria-label="Szukaj stanowisk" value={search} placeholder="Numer stołu lub lokalizacja…" onChange={e=>setSearch(e.target.value)}/></div></div><section className="panel"><div className="panel-heading"><h2>Stanowiska <span className="count-pill">{stations?.length??'—'}</span></h2></div>{resource.loading&&!resource.data?<Loading/>:stations?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Stanowisko</th><th>Lokalizacja</th><th>Urządzenia na stole</th><th/></tr></thead><tbody>{stations.map(s=><tr key={s.id}><td><Link className="table-title" href={`/workstations/${s.id}`}>{s.name}</Link></td><td>{s.path}</td><td>{s.assetCount} szt.</td><td><Link className="button button-secondary" href={`/workstations/${s.id}`}>Wyposażenie / wydruk <ArrowUpRight size={14}/></Link></td></tr>)}</tbody></table></div>:!resource.error&&<EmptyState title={search?'Brak pasujących stanowisk':'Dodaj pierwszy stół'} description="Zarejestruj np. 308A, a następnie przypisz ekran, komputer, klawiaturę i mysz."/>}</section>{creating&&<Modal title="Dodaj stanowisko / stół" onClose={()=>{if(!busy)setCreating(false);}}><form onSubmit={submit}><ErrorMessage message={error}/><fieldset className="plain-fieldset" disabled={busy}><Field label="Numer lub nazwa stanowiska *"><input required maxLength={160} placeholder="np. 308A" value={name} onChange={e=>setName(e.target.value)}/></Field><LocationPicker label="Gdzie znajduje się stół?" value={parentId} onChange={setParentId} emptyLabel="Poziom główny"/><p className="help-note">Stanowisko pojawi się również jako folder w drzewie lokalizacji.</p></fieldset><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={()=>setCreating(false)}>Anuluj</Button><Button disabled={busy}>{busy?'Zapisywanie…':'Dodaj stanowisko'}</Button></div></form></Modal>}</>;
}
function StationProfile({id}:{id:string}){
 const {user}=useApp(),resource=useResource<WorkstationEquipment>(`/api/workstations/${id}`),[adding,setAdding]=useState(false),station=resource.data?.location;
 if(resource.loading&&!resource.data)return <Loading/>;
 return <><Link className="back-link" href="/workstations"><ArrowLeft size={15}/>Stanowiska i stoły</Link><ErrorMessage message={resource.error} onRetry={resource.reload}/>{station&&<><PageHeader eyebrow="STANOWISKO / WYPOSAŻENIE" title={station.name} description={station.path} actions={hasPermission(user,'asset.create')&&<Button onClick={()=>setAdding(true)}><Plus size={16}/>Dodaj nowe urządzenie</Button>}/><div className="notice notice-info"><MapPin size={18}/><span>Sprzęt jest przypisany do stanowiska. Pracownicy korzystający ze stołu nie otrzymują automatycznie osobistego przypisania.</span></div><section className="panel"><div className="panel-heading"><h2>Wyposażenie stanowiska <span className="count-pill">{resource.data?.assets.length}</span></h2></div>{hasPermission(user,'asset.move')&&<div className="panel-body"><AssetLinker mode="location" targetId={id} targetName={station.name} onSaved={resource.reload}/></div>}{resource.data?.assets.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Urządzenie / model</th><th>Asset ID</th><th>Numer seryjny</th><th>Status</th><th>Osobisty odbiorca</th><th/></tr></thead><tbody>{resource.data.assets.map(a=><tr key={a.id}><td><Link className="table-title" href={`/asset/${a.assetId}`}>{a.name}</Link><small>{[a.manufacturer,a.model].filter(Boolean).join(' ')}</small></td><td className="mono">{a.assetId}</td><td className="mono">{a.serialNumber||'—'}</td><td><StatusBadge status={a.status}/></td><td>{a.owner||'Wyposażenie stanowiska'}</td><td><Link className="button button-secondary" href={`/asset/${a.assetId}`}>Karta urządzenia</Link></td></tr>)}</tbody></table></div>:<EmptyState title="Stanowisko nie ma jeszcze sprzętu" description="Dodaj nowy monitor, klawiaturę lub mysz albo przenieś istniejące urządzenie na ten stół."/>}</section><EquipmentDocuments target="workstation" id={id}/>{adding&&<AssetForm initialLocationId={id} onClose={()=>setAdding(false)} onSaved={()=>{setAdding(false);resource.reload();}}/>}</>}</>;
}
